package ai.uldren.loom

actual fun Loom.authenticatePassphrase(
    path: String,
    principal: String,
    principalPassphrase: String,
    passphrase: String?,
    kek: ByteArray?,
) = LoomNative.nativeAuthenticatePassphrase(
    path,
    principal,
    principalPassphrase.encodeToByteArray(),
    passphrase?.encodeToByteArray(),
    kek,
)

actual fun Loom.identityListJson(
    path: String,
    passphrase: String?,
    kek: ByteArray?,
    authPrincipal: String?,
    authPassphrase: String?,
): String = LoomNative.nativeIdentityListJson(
    path,
    passphrase?.encodeToByteArray(),
    kek,
    authPrincipal,
    authPassphrase?.encodeToByteArray(),
)

actual fun Loom.identityAddPrincipal(
    path: String,
    principalHandle: String,
    name: String,
    kind: String,
    passphrase: String?,
    kek: ByteArray?,
    authPrincipal: String?,
    authPassphrase: String?,
): String = LoomNative.nativeIdentityAddPrincipal(
    path,
    principalHandle,
    name,
    kind,
    passphrase?.encodeToByteArray(),
    kek,
    authPrincipal,
    authPassphrase?.encodeToByteArray(),
)

actual fun Loom.identityRenamePrincipalHandle(
    path: String,
    principal: String,
    principalHandle: String,
    passphrase: String?,
    kek: ByteArray?,
    authPrincipal: String?,
    authPassphrase: String?,
) = LoomNative.nativeIdentityRenamePrincipalHandle(
    path,
    principal,
    principalHandle,
    passphrase?.encodeToByteArray(),
    kek,
    authPrincipal,
    authPassphrase?.encodeToByteArray(),
)

actual fun Loom.identitySetPassphrase(
    path: String,
    principal: String,
    principalPassphrase: String,
    passphrase: String?,
    kek: ByteArray?,
    authPrincipal: String?,
    authPassphrase: String?,
) = LoomNative.nativeIdentitySetPassphrase(
    path,
    principal,
    principalPassphrase.encodeToByteArray(),
    passphrase?.encodeToByteArray(),
    kek,
    authPrincipal,
    authPassphrase?.encodeToByteArray(),
)

actual fun Loom.identityRemovePrincipal(
    path: String,
    principal: String,
    passphrase: String?,
    kek: ByteArray?,
    authPrincipal: String?,
    authPassphrase: String?,
) = LoomNative.nativeIdentityRemovePrincipal(
    path,
    principal,
    passphrase?.encodeToByteArray(),
    kek,
    authPrincipal,
    authPassphrase?.encodeToByteArray(),
)

actual fun Loom.identityAssignRole(
    path: String,
    principal: String,
    role: String,
    passphrase: String?,
    kek: ByteArray?,
    authPrincipal: String?,
    authPassphrase: String?,
) = LoomNative.nativeIdentityAssignRole(
    path,
    principal,
    role,
    passphrase?.encodeToByteArray(),
    kek,
    authPrincipal,
    authPassphrase?.encodeToByteArray(),
)

actual fun Loom.identityRevokeRole(
    path: String,
    principal: String,
    role: String,
    passphrase: String?,
    kek: ByteArray?,
    authPrincipal: String?,
    authPassphrase: String?,
): Boolean = LoomNative.nativeIdentityRevokeRole(
    path,
    principal,
    role,
    passphrase?.encodeToByteArray(),
    kek,
    authPrincipal,
    authPassphrase?.encodeToByteArray(),
)

actual fun Loom.identityCreateExternalCredential(
    path: String,
    principal: String,
    kind: String,
    label: String,
    issuer: String,
    subject: String,
    materialDigest: String?,
    passphrase: String?,
    kek: ByteArray?,
    authPrincipal: String?,
    authPassphrase: String?,
): String = LoomNative.nativeIdentityCreateExternalCredential(
    path,
    principal,
    kind,
    label,
    issuer,
    subject,
    materialDigest,
    passphrase?.encodeToByteArray(),
    kek,
    authPrincipal,
    authPassphrase?.encodeToByteArray(),
)

actual fun Loom.identityRevokeExternalCredential(
    path: String,
    credential: String,
    passphrase: String?,
    kek: ByteArray?,
    authPrincipal: String?,
    authPassphrase: String?,
) = LoomNative.nativeIdentityRevokeExternalCredential(
    path,
    credential,
    passphrase?.encodeToByteArray(),
    kek,
    authPrincipal,
    authPassphrase?.encodeToByteArray(),
)

actual fun Loom.identityAddPublicKey(
    path: String,
    principal: String,
    label: String,
    algorithm: String,
    publicKeyHex: String,
    passphrase: String?,
    kek: ByteArray?,
    authPrincipal: String?,
    authPassphrase: String?,
): String = LoomNative.nativeIdentityAddPublicKey(
    path,
    principal,
    label,
    algorithm,
    publicKeyHex,
    passphrase?.encodeToByteArray(),
    kek,
    authPrincipal,
    authPassphrase?.encodeToByteArray(),
)

actual fun Loom.identityRevokePublicKey(
    path: String,
    key: String,
    passphrase: String?,
    kek: ByteArray?,
    authPrincipal: String?,
    authPassphrase: String?,
) = LoomNative.nativeIdentityRevokePublicKey(
    path,
    key,
    passphrase?.encodeToByteArray(),
    kek,
    authPrincipal,
    authPassphrase?.encodeToByteArray(),
)

actual fun Loom.aclListJson(
    path: String,
    passphrase: String?,
    kek: ByteArray?,
    authPrincipal: String?,
    authPassphrase: String?,
): String = LoomNative.nativeAclListJson(
    path,
    passphrase?.encodeToByteArray(),
    kek,
    authPrincipal,
    authPassphrase?.encodeToByteArray(),
)

actual fun Loom.aclGrant(
    path: String,
    effect: Int,
    subject: String,
    workspace: String?,
    domain: String?,
    rightsMask: Int,
    passphrase: String?,
    kek: ByteArray?,
    authPrincipal: String?,
    authPassphrase: String?,
) = LoomNative.nativeAclGrant(
    path,
    effect,
    subject,
    workspace,
    domain,
    rightsMask,
    passphrase?.encodeToByteArray(),
    kek,
    authPrincipal,
    authPassphrase?.encodeToByteArray(),
)

actual fun Loom.aclRevoke(
    path: String,
    effect: Int,
    subject: String,
    workspace: String?,
    domain: String?,
    rightsMask: Int,
    passphrase: String?,
    kek: ByteArray?,
    authPrincipal: String?,
    authPassphrase: String?,
): Boolean = LoomNative.nativeAclRevoke(
    path,
    effect,
    subject,
    workspace,
    domain,
    rightsMask,
    passphrase?.encodeToByteArray(),
    kek,
    authPrincipal,
    authPassphrase?.encodeToByteArray(),
)

actual fun Loom.aclGrantScoped(
    path: String,
    effect: Int,
    subject: String,
    workspace: String?,
    domain: String?,
    rightsMask: Int,
    refGlob: String?,
    scopes: List<AclScope>,
    passphrase: String?,
    kek: ByteArray?,
    authPrincipal: String?,
    authPassphrase: String?,
) = LoomNative.nativeAclGrantScoped(
    path,
    effect,
    subject,
    workspace,
    domain,
    rightsMask,
    refGlob,
    scopes.map { it.kind }.toIntArray(),
    scopes.map { it.prefix }.toTypedArray(),
    passphrase?.encodeToByteArray(),
    kek,
    authPrincipal,
    authPassphrase?.encodeToByteArray(),
)

actual fun Loom.aclGrantScopedPredicate(
    path: String,
    effect: Int,
    subject: String,
    workspace: String?,
    domain: String?,
    rightsMask: Int,
    refGlob: String?,
    scopes: List<AclScope>,
    predicateCel: String?,
    passphrase: String?,
    kek: ByteArray?,
    authPrincipal: String?,
    authPassphrase: String?,
) = LoomNative.nativeAclGrantScopedPredicate(
    path,
    effect,
    subject,
    workspace,
    domain,
    rightsMask,
    refGlob,
    scopes.map { it.kind }.toIntArray(),
    scopes.map { it.prefix }.toTypedArray(),
    predicateCel,
    passphrase?.encodeToByteArray(),
    kek,
    authPrincipal,
    authPassphrase?.encodeToByteArray(),
)

actual fun Loom.aclRevokeScoped(
    path: String,
    effect: Int,
    subject: String,
    workspace: String?,
    domain: String?,
    rightsMask: Int,
    refGlob: String?,
    scopes: List<AclScope>,
    passphrase: String?,
    kek: ByteArray?,
    authPrincipal: String?,
    authPassphrase: String?,
): Boolean = LoomNative.nativeAclRevokeScoped(
    path,
    effect,
    subject,
    workspace,
    domain,
    rightsMask,
    refGlob,
    scopes.map { it.kind }.toIntArray(),
    scopes.map { it.prefix }.toTypedArray(),
    passphrase?.encodeToByteArray(),
    kek,
    authPrincipal,
    authPassphrase?.encodeToByteArray(),
)

actual fun Loom.aclRevokeScopedPredicate(
    path: String,
    effect: Int,
    subject: String,
    workspace: String?,
    domain: String?,
    rightsMask: Int,
    refGlob: String?,
    scopes: List<AclScope>,
    predicateCel: String?,
    passphrase: String?,
    kek: ByteArray?,
    authPrincipal: String?,
    authPassphrase: String?,
): Boolean = LoomNative.nativeAclRevokeScopedPredicate(
    path,
    effect,
    subject,
    workspace,
    domain,
    rightsMask,
    refGlob,
    scopes.map { it.kind }.toIntArray(),
    scopes.map { it.prefix }.toTypedArray(),
    predicateCel,
    passphrase?.encodeToByteArray(),
    kek,
    authPrincipal,
    authPassphrase?.encodeToByteArray(),
)

actual fun Loom.protectedRefListJson(
    path: String,
    workspace: String,
    passphrase: String?,
    kek: ByteArray?,
    authPrincipal: String?,
    authPassphrase: String?,
): String = LoomNative.nativeProtectedRefListJson(
    path,
    workspace,
    passphrase?.encodeToByteArray(),
    kek,
    authPrincipal,
    authPassphrase?.encodeToByteArray(),
)

actual fun Loom.protectedRefGetJson(
    path: String,
    workspace: String,
    refName: String,
    passphrase: String?,
    kek: ByteArray?,
    authPrincipal: String?,
    authPassphrase: String?,
): String = LoomNative.nativeProtectedRefGetJson(
    path,
    workspace,
    refName,
    passphrase?.encodeToByteArray(),
    kek,
    authPrincipal,
    authPassphrase?.encodeToByteArray(),
)

actual fun Loom.protectedRefSet(
    path: String,
    workspace: String,
    refName: String,
    fastForwardOnly: Boolean,
    signedCommitsRequired: Boolean,
    signedRefAdvanceRequired: Boolean,
    requiredReviewCount: Int,
    retentionLock: Boolean,
    governanceLock: Boolean,
    passphrase: String?,
    kek: ByteArray?,
    authPrincipal: String?,
    authPassphrase: String?,
) = LoomNative.nativeProtectedRefSet(
    path,
    workspace,
    refName,
    fastForwardOnly,
    signedCommitsRequired,
    signedRefAdvanceRequired,
    requiredReviewCount,
    retentionLock,
    governanceLock,
    passphrase?.encodeToByteArray(),
    kek,
    authPrincipal,
    authPassphrase?.encodeToByteArray(),
)

actual fun Loom.protectedRefRemove(
    path: String,
    workspace: String,
    refName: String,
    passphrase: String?,
    kek: ByteArray?,
    authPrincipal: String?,
    authPassphrase: String?,
): Boolean = LoomNative.nativeProtectedRefRemove(
    path,
    workspace,
    refName,
    passphrase?.encodeToByteArray(),
    kek,
    authPrincipal,
    authPassphrase?.encodeToByteArray(),
)
