package ai.uldren.loom

private fun String?.keyBytes(): ByteArray? = this?.encodeToByteArray()

actual fun Loom.lanesCreate(path: String, workspace: String, lane: ByteArray, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): ByteArray = LoomNative.nativeLanesCreate(path, workspace, lane, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.lanesGet(path: String, workspace: String, laneId: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): ByteArray? = LoomNative.nativeLanesGet(path, workspace, laneId, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.lanesList(path: String, workspace: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): ByteArray = LoomNative.nativeLanesList(path, workspace, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.lanesUpdate(path: String, workspace: String, laneId: String, title: String?, description: String?, laneStatus: String?, statusReport: String?, reviewerFeedback: String?, updatedBy: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): ByteArray = LoomNative.nativeLanesUpdate(path, workspace, laneId, title, description, laneStatus, statusReport, reviewerFeedback, updatedBy, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.lanesTicketAdd(path: String, workspace: String, laneId: String, ticketId: String, updatedBy: String, placement: String, anchor: String?, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): ByteArray = LoomNative.nativeLanesTicketAdd(path, workspace, laneId, ticketId, updatedBy, placement, anchor, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.lanesTicketRemove(path: String, workspace: String, laneId: String, ticketId: String, updatedBy: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): ByteArray = LoomNative.nativeLanesTicketRemove(path, workspace, laneId, ticketId, updatedBy, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
