package ai.uldren.loom

private fun String?.keyBytes(): ByteArray? = this?.encodeToByteArray()

actual fun Loom.studioReindexJson(path: String, workspace: String, profile: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeStudioReindexJson(path, workspace, profile, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.studioRevisionsRebuildJson(path: String, workspace: String, profile: String, dryRun: Boolean, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeStudioRevisionsRebuildJson(path, workspace, profile, dryRun, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.storeBundleImport(path: String, bundle: ByteArray, dryRun: Boolean, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): ByteArray = LoomNative.nativeStoreBundleImport(path, bundle, dryRun, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.auditCompact(path: String, throughSeq: Long, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): ByteArray {
    require(throughSeq >= 0) { "throughSeq must be non-negative" }
    return LoomNative.nativeAuditCompact(path, throughSeq, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
}
actual fun Loom.storeMaintenanceStatus(path: String, request: ByteArray, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): ByteArray = LoomNative.nativeStoreMaintenanceStatus(path, request, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.storeMaintenancePolicySet(path: String, update: ByteArray, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): ByteArray = LoomNative.nativeStoreMaintenancePolicySet(path, update, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.storeMaintenanceRun(path: String, request: ByteArray, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): ByteArray = LoomNative.nativeStoreMaintenanceRun(path, request, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.importTableCsv(path: String, workspace: String, sourceScope: String, csvPayload: ByteArray, database: String, table: String, schema: String, primaryKey: String, mode: String, commit: Boolean, author: String?, message: String?, dryRun: Boolean, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): ByteArray = LoomNative.nativeImportTableCsv(path, workspace, sourceScope, csvPayload, database, table, schema, primaryKey, mode, commit, author, message, dryRun, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.importRedmine(path: String, workspace: String, profile: String, sourceScope: String, snapshotPayload: ByteArray, fieldPolicy: String, dryRun: Boolean, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): ByteArray = LoomNative.nativeImportRedmine(path, workspace, profile, sourceScope, snapshotPayload, fieldPolicy, dryRun, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.importAsana(path: String, workspace: String, profile: String, sourceScope: String, snapshotPayload: ByteArray, fieldPolicy: String, dryRun: Boolean, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): ByteArray = LoomNative.nativeImportAsana(path, workspace, profile, sourceScope, snapshotPayload, fieldPolicy, dryRun, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.importJira(path: String, workspace: String, profile: String, sourceScope: String, snapshotPayload: ByteArray, fieldPolicy: String, dryRun: Boolean, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): ByteArray = LoomNative.nativeImportJira(path, workspace, profile, sourceScope, snapshotPayload, fieldPolicy, dryRun, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.importConfluence(path: String, workspace: String, profile: String, sourceScope: String, snapshotPayload: ByteArray, defaultSpace: String, dryRun: Boolean, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): ByteArray = LoomNative.nativeImportConfluence(path, workspace, profile, sourceScope, snapshotPayload, defaultSpace, dryRun, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.importSlack(path: String, workspace: String, profile: String, sourceScope: String, snapshotPayload: ByteArray, dryRun: Boolean, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): ByteArray = LoomNative.nativeImportSlack(path, workspace, profile, sourceScope, snapshotPayload, dryRun, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.importDrive(path: String, workspace: String, profile: String, sourceScope: String, archivePayload: ByteArray, dryRun: Boolean, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): ByteArray = LoomNative.nativeImportDrive(path, workspace, profile, sourceScope, archivePayload, dryRun, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.importMarkdown(path: String, workspace: String, profile: String, sourceScope: String, archivePayload: ByteArray, space: String, dryRun: Boolean, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): ByteArray = LoomNative.nativeImportMarkdown(path, workspace, profile, sourceScope, archivePayload, space, dryRun, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.importNotion(path: String, workspace: String, profile: String, sourceScope: String, snapshotPayload: ByteArray, defaultSpace: String, dryRun: Boolean, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): ByteArray = LoomNative.nativeImportNotion(path, workspace, profile, sourceScope, snapshotPayload, defaultSpace, dryRun, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.inferenceInstanceCreateJson(path: String, workspace: String, name: String, model: String, kind: String, runtime: String, preset: String?, settingsJson: String?, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeInferenceInstanceCreateJson(path, workspace, name, model, kind, runtime, preset, settingsJson, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.inferenceInstanceUpdateJson(path: String, workspace: String, name: String, preset: String?, settingsJson: String?, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeInferenceInstanceUpdateJson(path, workspace, name, preset, settingsJson, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.inferenceInstanceDeleteJson(path: String, workspace: String, name: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeInferenceInstanceDeleteJson(path, workspace, name, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.serveListenerConfigureJson(path: String, requestJson: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeServeListenerConfigureJson(path, requestJson, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.serveListenerListJson(path: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeServeListenerListJson(path, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.serveListenerSetEnabledJson(path: String, listenerId: String, enabled: Boolean, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeServeListenerSetEnabledJson(path, listenerId, enabled, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.serveListenerRemoveJson(path: String, listenerId: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeServeListenerRemoveJson(path, listenerId, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.serveWebRouteListJson(path: String, listenerId: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeServeWebRouteListJson(path, listenerId, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.serveWebRouteSetJson(path: String, requestJson: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeServeWebRouteSetJson(path, requestJson, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.serveWebRouteRemoveJson(path: String, listenerId: String, routeId: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeServeWebRouteRemoveJson(path, listenerId, routeId, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
