package ai.uldren.loom

private fun String?.keyBytes(): ByteArray? = this?.encodeToByteArray()

actual fun Loom.ticketsProjectCreateJson(path: String, workspace: String, ticketWorkspaceId: String, projectId: String, keyPrefix: String, name: String, expectedRoot: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeTicketsProjectCreateJson(path, workspace, ticketWorkspaceId, projectId, keyPrefix, name, expectedRoot, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.ticketsProjectRekeyJson(path: String, workspace: String, ticketWorkspaceId: String, projectId: String, keyPrefix: String, expectedRoot: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeTicketsProjectRekeyJson(path, workspace, ticketWorkspaceId, projectId, keyPrefix, expectedRoot, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.ticketsProjectSettingsGetJson(path: String, workspace: String, ticketWorkspaceId: String, projectId: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeTicketsProjectSettingsGetJson(path, workspace, ticketWorkspaceId, projectId, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.ticketsProjectSettingsSetJson(path: String, workspace: String, ticketWorkspaceId: String, projectId: String, defaultProjection: String?, enableProjectionsJson: String, disableProjectionsJson: String, actorEnforcement: String?, projectOwnerPrincipal: String?, clearProjectOwnerPrincipal: Boolean, acceptanceAuthoritiesJson: String?, expectedRoot: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeTicketsProjectSettingsSetJson(path, workspace, ticketWorkspaceId, projectId, defaultProjection, enableProjectionsJson, disableProjectionsJson, actorEnforcement, projectOwnerPrincipal, clearProjectOwnerPrincipal, acceptanceAuthoritiesJson, expectedRoot, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.ticketsFieldsJson(path: String, workspace: String, ticketWorkspaceId: String, projectId: String, projection: String, operation: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeTicketsFieldsJson(path, workspace, ticketWorkspaceId, projectId, projection, operation, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.ticketsFieldPutJson(path: String, workspace: String, ticketWorkspaceId: String, projectId: String, fieldId: String, key: String, name: String, description: String?, fieldType: String, optionSet: String?, maxLength: Int?, required: Boolean, searchable: Boolean, orderable: Boolean, cardinality: String, applicableTypeIdsJson: String, expectedRoot: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeTicketsFieldPutJson(path, workspace, ticketWorkspaceId, projectId, fieldId, key, name, description, fieldType, optionSet, maxLength ?: 0, maxLength != null, required, searchable, orderable, cardinality, applicableTypeIdsJson, expectedRoot, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.ticketsFieldRetireJson(path: String, workspace: String, ticketWorkspaceId: String, projectId: String, fieldId: String, expectedRoot: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeTicketsFieldRetireJson(path, workspace, ticketWorkspaceId, projectId, fieldId, expectedRoot, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.ticketsCreateJson(path: String, workspace: String, ticketWorkspaceId: String, projectId: String, ticketType: String, externalSource: String?, externalId: String?, fieldsJson: String, policyLabelsJson: String, expectedRoot: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeTicketsCreateJson(path, workspace, ticketWorkspaceId, projectId, ticketType, externalSource, externalId, fieldsJson, policyLabelsJson, expectedRoot, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.ticketsUpdateJson(path: String, workspace: String, ticketWorkspaceId: String, ticketId: String, setFieldsJson: String, deleteFieldsJson: String, action: String?, targetStatus: String?, observedSourceStatus: String?, observedWorkflowVersion: String?, assignee: String?, expectedRoot: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?, commentId: String?, commentType: String?, commentBody: String?, commentsJson: String?, relationSetsJson: String?, relationRemovesJson: String?): String = LoomNative.nativeTicketsUpdateJson(path, workspace, ticketWorkspaceId, ticketId, setFieldsJson, deleteFieldsJson, action, targetStatus, observedSourceStatus, observedWorkflowVersion, assignee, expectedRoot, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes(), commentId, commentType, commentBody, commentsJson, relationSetsJson, relationRemovesJson)
actual fun Loom.ticketsDeleteJson(path: String, workspace: String, ticketWorkspaceId: String, ticketId: String, expectedRoot: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeTicketsDeleteJson(path, workspace, ticketWorkspaceId, ticketId, expectedRoot, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.ticketsRelationSetJson(path: String, workspace: String, ticketWorkspaceId: String, ticketId: String, relationId: String, kind: String, targetId: String, expectedRoot: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeTicketsRelationSetJson(path, workspace, ticketWorkspaceId, ticketId, relationId, kind, targetId, expectedRoot, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.ticketsRelationRemoveJson(path: String, workspace: String, ticketWorkspaceId: String, ticketId: String, relationId: String, expectedRoot: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeTicketsRelationRemoveJson(path, workspace, ticketWorkspaceId, ticketId, relationId, expectedRoot, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.ticketsGetJson(path: String, workspace: String, ticketWorkspaceId: String, ticketId: String, projection: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeTicketsGetJson(path, workspace, ticketWorkspaceId, ticketId, projection, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.ticketsListJson(path: String, workspace: String, ticketWorkspaceId: String, projection: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeTicketsListJson(path, workspace, ticketWorkspaceId, projection, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
actual fun Loom.ticketsHistoryJson(path: String, workspace: String, ticketWorkspaceId: String, ticketId: String, passphrase: String?, kek: ByteArray?, authPrincipal: String?, authPassphrase: String?): String = LoomNative.nativeTicketsHistoryJson(path, workspace, ticketWorkspaceId, ticketId, passphrase.keyBytes(), kek, authPrincipal, authPassphrase.keyBytes())
