"""Python binding for Uldren Loom - a universal, content-addressed, versioned filesystem.

Wraps the Uldren Loom Rust core through a native extension built with PyO3. Licensed under
BUSL-1.1 (see the repository LICENSE). (c) Uldren Technologies LLC.
"""

import asyncio
import json
from dataclasses import dataclass

from ._native import (
    LoomSql,
    LoomSqlBatch,
    acl_grant,
    acl_grant_scoped,
    acl_list_json,
    acl_revoke,
    acl_revoke_scoped,
    protected_ref_get_json,
    protected_ref_list_json,
    protected_ref_remove,
    protected_ref_set,
    archive_export,
    archive_import,
    fs_export,
    fs_import,
    authenticate_passphrase,
    blob_digest,
    capabilities,
    runtime_profile,
    studio_surface_catalog_json,
    meetings_import_snapshot,
    meetings_source_read,
    drive_apply_retention_json,
    drive_apply_share_expiry_json,
    drive_commit_upload_json,
    drive_create_folder_json,
    drive_create_upload_json,
    drive_delete_json,
    drive_grant_share_json,
    drive_list_conflicts_json,
    drive_list_json,
    drive_list_retention_json,
    drive_list_shares_json,
    drive_list_versions_json,
    drive_move_json,
    drive_pin_retention_json,
    drive_read_file,
    drive_rename_json,
    drive_resolve_conflict_json,
    drive_revoke_share_json,
    drive_stat_json,
    drive_unpin_retention_json,
    drive_upload_chunk_json,
    tickets_comment_add_json,
    tickets_comment_delete_json,
    tickets_comment_update_json,
    tickets_comments_json,
    tickets_create_json,
    tickets_delete_json,
    tickets_field_put_json,
    tickets_field_retire_json,
    tickets_fields_json,
    tickets_get_json,
    tickets_history_json,
    tickets_list_json,
    tickets_project_create_json,
    tickets_project_rekey_json,
    tickets_project_settings_get_json,
    tickets_project_settings_set_json,
    tickets_relation_remove_json,
    tickets_relation_set_json,
    tickets_update_json,
    chat_add_reaction_json,
    chat_agent_reply_json,
    chat_claim_task_json,
    chat_complete_task_json,
    chat_create_channel_json,
    chat_create_task_json,
    chat_create_thread_json,
    chat_cursor_json,
    chat_edit_message_json,
    chat_emoji_list_json,
    chat_emoji_register_json,
    chat_emoji_unregister_json,
    chat_fetch_events_json,
    chat_invoke_agent_json,
    chat_list_channels_json,
    chat_messages_json,
    chat_post_message_json,
    chat_redact_message_json,
    chat_remove_reaction_json,
    chat_rename_channel_json,
    chat_request_handoff_json,
    chat_update_cursor_json,
    cas_delete,
    cas_get,
    cas_has,
    cas_list_json,
    cas_put,
    create_loom,
    exec_cbor,
    daemon_pin_add,
    daemon_pin_remove,
    daemon_session_attach,
    daemon_session_detach,
    daemon_status_json,
    sql_index_scan,
    sql_index_scan_at,
    key_add_wrap_keyed,
    key_add_wrap_with_kek,
    key_remove_wrap,
    lock_acquire_json,
    lock_refresh_json,
    lock_release,
    kv_delete,
    kv_get,
    kv_list,
    kv_put,
    kv_range,
    lanes_create,
    lanes_delete,
    lanes_get,
    lanes_list,
    lanes_update,
    lanes_ticket_add,
    lanes_ticket_remove,
    lanes_ticket_transfer,
    pages_create_json,
    pages_get_json,
    pages_history_json,
    pages_list_json,
    pages_publish_json,
    pages_update_json,
    spaces_create_json,
    spaces_get_json,
    spaces_list_json,
    structures_add_node_json,
    structures_bind_json,
    structures_create_json,
    structures_decompose_to_tickets_json,
    structures_get_json,
    structures_link_node_json,
    structures_list_json,
    structures_move_node_json,
    structures_update_node_json,
    graph_upsert_node,
    graph_get_node,
    graph_remove_node,
    graph_upsert_edge,
    graph_get_edge,
    graph_remove_edge,
    graph_neighbors,
    graph_out_edges,
    graph_in_edges,
    graph_reachable,
    graph_shortest_path,
    identity_add_principal,
    identity_rename_principal_handle,
    identity_add_public_key,
    identity_assign_role,
    identity_create_external_credential,
    identity_list_json,
    identity_remove_principal,
    identity_revoke_external_credential,
    identity_revoke_public_key,
    identity_revoke_role,
    identity_set_passphrase,
    vector_create,
    vector_upsert,
    vector_upsert_source,
    vector_get,
    vector_source_text,
    vector_embedding_model,
    vector_ids,
    vector_metadata_index_keys,
    vector_create_metadata_index,
    vector_drop_metadata_index,
    vector_delete,
    vector_search,
    vector_search_policy,
    columnar_create,
    columnar_append,
    columnar_scan,
    columnar_columns,
    columnar_rows,
    columnar_compact,
    columnar_inspect,
    columnar_source_digest,
    columnar_select,
    columnar_aggregate,
    dataframe_create,
    dataframe_collect,
    dataframe_preview,
    dataframe_materialize,
    dataframe_plan_digest,
    dataframe_source_digests,
    search_create,
    search_index,
    search_get,
    search_delete,
    search_ids,
    search_remap,
    search_query,
    doc_put_text,
    doc_get_text,
    doc_put_binary,
    doc_get_binary,
    doc_delete,
    doc_list_binary,
    doc_index_create,
    doc_index_create_json,
    doc_index_drop,
    doc_index_rebuild,
    doc_index_list_json,
    doc_index_status_json,
    doc_find_json,
    doc_query_json,
    ts_put,
    ts_get,
    ts_range,
    ts_latest,
    ledger_append,
    ledger_get,
    ledger_head,
    ledger_len,
    ledger_verify,
    cal_create_collection,
    cal_delete_collection,
    cal_list_collections,
    cal_put_entry,
    cal_get_entry,
    cal_delete_entry,
    cal_list_entries,
    cal_range,
    cal_search,
    cal_entry_ics,
    cal_put_ics,
    card_create_book,
    card_delete_book,
    card_list_books,
    card_put_entry,
    card_get_entry,
    card_delete_entry,
    card_list_entries,
    card_search,
    card_entry_vcard,
    card_put_vcard,
    car_export,
    car_import,
    mail_create_mailbox,
    mail_delete_mailbox,
    mail_list_mailboxes,
    mail_ingest_message,
    mail_get_message,
    mail_to_eml,
    mail_delete_message,
    mail_list_messages,
    mail_get_flags,
    mail_set_flags,
    mail_search,
    merge_abort,
    merge_conflicts,
    merge_continue,
    merge_in_progress,
    merge_resolve,
    stage,
    stage_all,
    unstage,
    status_json,
    commit_staged,
    write_file,
    read_file,
    append_file,
    remove_file,
    symlink,
    read_link,
    restore_file,
    restore_path,
    cherry_pick,
    revert,
    rebase,
    squash,
    read_at,
    write_at,
    truncate_file,
    file_open,
    file_read,
    file_read_at,
    file_write,
    file_write_at,
    file_truncate,
    file_flush,
    file_stat,
    file_close,
    tag_create,
    tag_list,
    tag_target,
    tag_delete,
    tag_rename,
    workspace_create,
    workspace_delete,
    workspace_list_json,
    workspace_rename,
    queue_append,
    queue_consumer_advance,
    queue_consumer_position,
    queue_consumer_read,
    queue_consumer_reset,
    queue_get,
    queue_len,
    queue_range,
    sql_read_table,
    sql_read_table_at,
    result_to_bridge_json,
    result_to_json,
    sql_blame,
    sql_diff,
    sql_table_diff,
    vcs_blame,
    vcs_diff,
    watch_subscribe,
    watch_poll,
    version,
)

__all__ = [
    "LoomSql",
    "LoomSqlBatch",
    "AsyncLoomSql",
    "acl_grant",
    "acl_grant_scoped",
    "acl_list_json",
    "acl_revoke",
    "acl_revoke_scoped",
    "protected_ref_get_json",
    "protected_ref_list_json",
    "protected_ref_remove",
    "protected_ref_set",
    "archive_export",
    "archive_import",
    "fs_export",
    "fs_import",
    "authenticate_passphrase",
    "blob_digest",
    "capabilities",
    "runtime_profile",
    "studio_surface_catalog_json",
    "meetings_import_snapshot",
    "meetings_source_read",
    "drive_apply_retention_json",
    "drive_apply_share_expiry_json",
    "drive_commit_upload_json",
    "drive_create_folder_json",
    "drive_create_upload_json",
    "drive_delete_json",
    "drive_grant_share_json",
    "drive_list_conflicts_json",
    "drive_list_json",
    "drive_list_retention_json",
    "drive_list_shares_json",
    "drive_list_versions_json",
    "drive_move_json",
    "drive_pin_retention_json",
    "drive_read_file",
    "drive_rename_json",
    "drive_resolve_conflict_json",
    "drive_revoke_share_json",
    "drive_stat_json",
    "drive_unpin_retention_json",
    "drive_upload_chunk_json",
    "tickets_comment_add_json",
    "tickets_comment_delete_json",
    "tickets_comment_update_json",
    "tickets_comments_json",
    "tickets_create_json",
    "tickets_delete_json",
    "tickets_field_put_json",
    "tickets_field_retire_json",
    "tickets_fields_json",
    "tickets_get_json",
    "tickets_history_json",
    "tickets_list_json",
    "tickets_project_create_json",
    "tickets_project_rekey_json",
    "tickets_project_settings_get_json",
    "tickets_project_settings_set_json",
    "tickets_relation_remove_json",
    "tickets_relation_set_json",
    "tickets_update_json",
    "chat_add_reaction_json",
    "chat_agent_reply_json",
    "chat_claim_task_json",
    "chat_complete_task_json",
    "chat_create_channel_json",
    "chat_create_task_json",
    "chat_create_thread_json",
    "chat_cursor_json",
    "chat_edit_message_json",
    "chat_emoji_list_json",
    "chat_emoji_register_json",
    "chat_emoji_unregister_json",
    "chat_fetch_events_json",
    "chat_invoke_agent_json",
    "chat_list_channels_json",
    "chat_messages_json",
    "chat_post_message_json",
    "chat_redact_message_json",
    "chat_remove_reaction_json",
    "chat_rename_channel_json",
    "chat_request_handoff_json",
    "chat_update_cursor_json",
    "cas_delete",
    "cas_get",
    "cas_has",
    "cas_list_json",
    "cas_put",
    "create_loom",
    "exec_cbor",
    "daemon_pin_add",
    "daemon_pin_remove",
    "daemon_session_attach",
    "daemon_session_detach",
    "daemon_status_json",
    "sql_index_scan",
    "key_add_wrap_keyed",
    "key_add_wrap_with_kek",
    "key_remove_wrap",
    "LockToken",
    "LockGuard",
    "lock_acquire",
    "lock_acquire_json",
    "lock_try_acquire",
    "lock_refresh",
    "lock_refresh_json",
    "lock_release",
    "lock_release_token",
    "lock_guard",
    "kv_delete",
    "kv_get",
    "kv_list",
    "kv_put",
    "kv_range",
    "lanes_create",
    "lanes_delete",
    "lanes_get",
    "lanes_list",
    "lanes_update",
    "lanes_ticket_add",
    "lanes_ticket_remove",
    "lanes_ticket_transfer",
    "pages_create_json",
    "pages_get_json",
    "pages_history_json",
    "pages_list_json",
    "pages_publish_json",
    "pages_update_json",
    "spaces_create_json",
    "spaces_get_json",
    "spaces_list_json",
    "structures_add_node_json",
    "structures_bind_json",
    "structures_create_json",
    "structures_decompose_to_tickets_json",
    "structures_get_json",
    "structures_link_node_json",
    "structures_list_json",
    "structures_move_node_json",
    "structures_update_node_json",
    "graph_upsert_node",
    "graph_get_node",
    "graph_remove_node",
    "graph_upsert_edge",
    "graph_get_edge",
    "graph_remove_edge",
    "graph_neighbors",
    "graph_out_edges",
    "graph_in_edges",
    "graph_reachable",
    "graph_shortest_path",
    "identity_add_principal",
    "identity_rename_principal_handle",
    "identity_add_public_key",
    "identity_assign_role",
    "identity_create_external_credential",
    "identity_list_json",
    "identity_remove_principal",
    "identity_revoke_external_credential",
    "identity_revoke_public_key",
    "identity_revoke_role",
    "identity_set_passphrase",
    "vector_create",
    "vector_upsert",
    "vector_upsert_source",
    "vector_get",
    "vector_source_text",
    "vector_embedding_model",
    "vector_ids",
    "vector_metadata_index_keys",
    "vector_create_metadata_index",
    "vector_drop_metadata_index",
    "vector_delete",
    "vector_search",
    "vector_search_policy",
    "columnar_create",
    "columnar_append",
    "columnar_scan",
    "columnar_columns",
    "columnar_rows",
    "columnar_compact",
    "columnar_inspect",
    "columnar_source_digest",
    "columnar_select",
    "columnar_aggregate",
    "dataframe_create",
    "dataframe_collect",
    "dataframe_preview",
    "dataframe_materialize",
    "dataframe_plan_digest",
    "dataframe_source_digests",
    "search_create",
    "search_index",
    "search_get",
    "search_delete",
    "search_ids",
    "search_remap",
    "search_query",
    "doc_put_text",
    "doc_get_text",
    "doc_put_binary",
    "doc_get_binary",
    "doc_delete",
    "doc_list_binary",
    "doc_index_create",
    "doc_index_create_json",
    "doc_index_drop",
    "doc_index_rebuild",
    "doc_index_list_json",
    "doc_index_status_json",
    "doc_find_json",
    "doc_query_json",
    "ts_put",
    "ts_get",
    "ts_range",
    "ts_latest",
    "ledger_append",
    "ledger_get",
    "ledger_head",
    "ledger_len",
    "ledger_verify",
    "cal_create_collection",
    "cal_delete_collection",
    "cal_list_collections",
    "cal_put_entry",
    "cal_get_entry",
    "cal_delete_entry",
    "cal_list_entries",
    "cal_range",
    "cal_search",
    "cal_entry_ics",
    "cal_put_ics",
    "card_create_book",
    "card_delete_book",
    "card_list_books",
    "card_put_entry",
    "card_get_entry",
    "card_delete_entry",
    "card_list_entries",
    "card_search",
    "card_entry_vcard",
    "card_put_vcard",
    "car_export",
    "car_import",
    "mail_create_mailbox",
    "mail_delete_mailbox",
    "mail_list_mailboxes",
    "mail_ingest_message",
    "mail_get_message",
    "mail_to_eml",
    "mail_delete_message",
    "mail_list_messages",
    "mail_get_flags",
    "mail_set_flags",
    "mail_search",
    "merge_abort",
    "merge_conflicts",
    "merge_continue",
    "merge_in_progress",
    "merge_resolve",
    "stage",
    "stage_all",
    "unstage",
    "status_json",
    "commit_staged",
    "write_file",
    "read_file",
    "append_file",
    "remove_file",
    "symlink",
    "read_link",
    "restore_file",
    "restore_path",
    "cherry_pick",
    "revert",
    "rebase",
    "squash",
    "read_at",
    "write_at",
    "truncate_file",
    "file_open",
    "file_read",
    "file_read_at",
    "file_write",
    "file_write_at",
    "file_truncate",
    "file_flush",
    "file_stat",
    "file_close",
    "tag_create",
    "tag_list",
    "tag_target",
    "tag_delete",
    "tag_rename",
    "workspace_create",
    "workspace_delete",
    "workspace_list_json",
    "workspace_rename",
    "queue_append",
    "queue_consumer_advance",
    "queue_consumer_position",
    "queue_consumer_read",
    "queue_consumer_reset",
    "queue_get",
    "queue_len",
    "queue_range",
    "sql_read_table",
    "sql_read_table_at",
    "result_to_bridge_json",
    "result_to_json",
    "sql_blame",
    "sql_diff",
    "sql_index_scan_at",
    "sql_table_diff",
    "vcs_blame",
    "vcs_diff",
    "watch_subscribe",
    "watch_poll",
    "version",
]

@dataclass(frozen=True)
class Fence:
    authority: int
    epoch: int
    sequence: int

    def low(self) -> int:
        return self.sequence

    def high(self) -> int:
        return (self.authority << 32) | self.epoch


@dataclass(frozen=True)
class LockToken:
    key: str
    principal: str
    session: str
    mode: str
    permits: int
    capacity: int
    fence: Fence
    lease_deadline_ms: int


def _lock_token_from_json(payload: str) -> LockToken:
    data = json.loads(payload)
    fence = data["fence"]
    return LockToken(
        key=data["key"],
        principal=data["principal"],
        session=data["session"],
        mode=data["mode"],
        permits=int(data["permits"]),
        capacity=int(data["capacity"]),
        fence=Fence(
            authority=int(fence["authority"]),
            epoch=int(fence["epoch"]),
            sequence=int(fence["sequence"]),
        ),
        lease_deadline_ms=int(data["lease_deadline_ms"]),
    )


def lock_acquire(
    path: str,
    key: str,
    principal: str,
    session: str,
    mode: str = "exclusive",
    permits: int = 1,
    capacity: int = 1,
    lease_ms: int = 60000,
    wait_ms: int | None = None,
) -> LockToken:
    return _lock_token_from_json(
        lock_acquire_json(path, key, principal, session, mode, permits, capacity, lease_ms, wait_ms)
    )


def lock_try_acquire(
    path: str,
    key: str,
    principal: str,
    session: str,
    mode: str = "exclusive",
    permits: int = 1,
    capacity: int = 1,
    lease_ms: int = 60000,
) -> LockToken:
    return lock_acquire(path, key, principal, session, mode, permits, capacity, lease_ms, 0)


def lock_refresh(path: str, token: LockToken, lease_ms: int = 60000) -> LockToken:
    return _lock_token_from_json(
        lock_refresh_json(
            path,
            token.key,
            token.principal,
            token.session,
            token.mode,
            token.permits,
            token.capacity,
            token.fence.low(),
            token.fence.high(),
            lease_ms,
        )
    )


def lock_release_token(path: str, token: LockToken) -> None:
    lock_release(
        path,
        token.key,
        token.principal,
        token.session,
        token.mode,
        token.permits,
        token.capacity,
        token.fence.low(),
        token.fence.high(),
    )


class LockGuard:
    def __init__(self, path: str, token: LockToken) -> None:
        self.path = path
        self.token = token
        self._released = False

    def refresh(self, lease_ms: int = 60000) -> LockToken:
        self.token = lock_refresh(self.path, self.token, lease_ms)
        return self.token

    def release(self) -> None:
        if not self._released:
            lock_release_token(self.path, self.token)
            self._released = True

    def __enter__(self) -> "LockGuard":
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        self.release()


def lock_guard(
    path: str,
    key: str,
    principal: str,
    session: str,
    mode: str = "exclusive",
    permits: int = 1,
    capacity: int = 1,
    lease_ms: int = 60000,
    wait_ms: int | None = None,
) -> LockGuard:
    token = lock_acquire(path, key, principal, session, mode, permits, capacity, lease_ms, wait_ms)
    return LockGuard(path, token)


class AsyncLoomSql:
    """An ``asyncio`` wrapper around :class:`LoomSql` (the asyncio form of the async ABI).

    The native ``exec`` / ``exec_bytes`` / ``exec_json`` / ``commit`` release the GIL for their blocking
    engine work, so :func:`asyncio.to_thread` runs each truly off the event loop - the loop never blocks
    on engine I/O. This needs no third-party dependency; it is the idiomatic stdlib path. Each call still
    opens the ``.loom``, runs, and closes (the engine's per-op model), so instances are cheap and coexist.
    """

    def __init__(self, loom_path: str, ns_name: str, db: str) -> None:
        self._db = LoomSql(loom_path, ns_name, db)

    async def exec(self, sql: str):
        """Run SQL and return typed results, off the event loop. See :meth:`LoomSql.exec`."""
        return await asyncio.to_thread(self._db.exec, sql)

    async def exec_json(self, sql: str) -> str:
        """Run SQL and return the JSON debug form, off the event loop."""
        return await asyncio.to_thread(self._db.exec_json, sql)

    async def exec_bytes(self, sql: str) -> bytes:
        """Run SQL and return canonical-CBOR bytes, off the event loop."""
        return await asyncio.to_thread(self._db.exec_bytes, sql)

    async def commit(self, message: str, author: str) -> str:
        """Commit the staged state, off the event loop; returns the new commit's content address."""
        return await asyncio.to_thread(self._db.commit, message, author)
