package ai.uldren.loom

expect fun Loom.chatCreateChannelJson(path: String, workspace: String, chatWorkspaceId: String, channelId: String, channelHandle: String, name: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.chatRenameChannelJson(path: String, workspace: String, chatWorkspaceId: String, selector: String, channelHandle: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.chatListChannelsJson(path: String, workspace: String, chatWorkspaceId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.chatPostMessageJson(path: String, workspace: String, chatWorkspaceId: String, channelId: String, messageId: String, threadId: String? = null, bodyText: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.chatEditMessageJson(path: String, workspace: String, chatWorkspaceId: String, channelId: String, messageId: String, bodyText: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.chatRedactMessageJson(path: String, workspace: String, chatWorkspaceId: String, channelId: String, messageId: String, reason: String? = null, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.chatCreateThreadJson(path: String, workspace: String, chatWorkspaceId: String, channelId: String, threadId: String, parentMessageId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.chatCreateTaskJson(path: String, workspace: String, chatWorkspaceId: String, channelId: String, taskId: String, messageId: String, title: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.chatClaimTaskJson(path: String, workspace: String, chatWorkspaceId: String, channelId: String, taskId: String, claimId: String, leaseToken: String? = null, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.chatCompleteTaskJson(path: String, workspace: String, chatWorkspaceId: String, channelId: String, taskId: String, claimId: String, resultMessageId: String? = null, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.chatInvokeAgentJson(path: String, workspace: String, chatWorkspaceId: String, channelId: String, invocationId: String, agentPrincipal: String, sourceMessageIdsJson: String, promptText: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.chatAgentReplyJson(path: String, workspace: String, chatWorkspaceId: String, channelId: String, invocationId: String, messageId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.chatRequestHandoffJson(path: String, workspace: String, chatWorkspaceId: String, channelId: String, handoffId: String, fromAgentPrincipal: String, toPrincipal: String? = null, reason: String? = null, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.chatAddReactionJson(path: String, workspace: String, chatWorkspaceId: String, channelId: String, messageId: String, kind: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.chatRemoveReactionJson(path: String, workspace: String, chatWorkspaceId: String, channelId: String, messageId: String, kind: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.chatEmojiListJson(path: String, workspace: String, chatWorkspaceId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.chatEmojiRegisterJson(path: String, workspace: String, chatWorkspaceId: String, kind: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.chatEmojiUnregisterJson(path: String, workspace: String, chatWorkspaceId: String, kind: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.chatMessagesJson(path: String, workspace: String, chatWorkspaceId: String, channelId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.chatCursorJson(path: String, workspace: String, chatWorkspaceId: String, channelId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.chatUpdateCursorJson(path: String, workspace: String, chatWorkspaceId: String, channelId: String, nextSequence: ULong, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.chatFetchEventsJson(path: String, workspace: String, chatWorkspaceId: String, channelId: String, fromSequence: ULong, max: UInt, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
