package ai.uldren.loom

expect fun Loom.driveListJson(path: String, workspace: String, driveWorkspaceId: String, folderId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.driveStatJson(path: String, workspace: String, driveWorkspaceId: String, folderId: String, name: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.driveReadFile(path: String, workspace: String, driveWorkspaceId: String, fileId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): ByteArray
expect fun Loom.driveListVersionsJson(path: String, workspace: String, driveWorkspaceId: String, fileId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.driveListConflictsJson(path: String, workspace: String, driveWorkspaceId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.driveListSharesJson(path: String, workspace: String, driveWorkspaceId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.driveListRetentionJson(path: String, workspace: String, driveWorkspaceId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.driveCreateFolderJson(path: String, workspace: String, driveWorkspaceId: String, parentFolderId: String, folderId: String, name: String, expectedRoot: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.driveCreateUploadJson(path: String, workspace: String, driveWorkspaceId: String, uploadId: String, parentFolderId: String, name: String, fileId: String, expectedRoot: String, createdAtMs: Long, replaceFile: Boolean, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.driveUploadChunkJson(path: String, workspace: String, driveWorkspaceId: String, uploadId: String, chunk: ByteArray, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.driveCommitUploadJson(path: String, workspace: String, driveWorkspaceId: String, uploadId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.driveRenameJson(path: String, workspace: String, driveWorkspaceId: String, folderId: String, nodeId: String, newName: String, expectedRoot: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.driveMoveJson(path: String, workspace: String, driveWorkspaceId: String, sourceFolderId: String, targetFolderId: String, nodeId: String, expectedRoot: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.driveDeleteJson(path: String, workspace: String, driveWorkspaceId: String, folderId: String, nodeId: String, expectedRoot: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.driveResolveConflictJson(path: String, workspace: String, driveWorkspaceId: String, conflictId: String, resolution: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.driveGrantShareJson(path: String, workspace: String, driveWorkspaceId: String, grantId: String, targetKind: String, targetId: String, principal: String, role: String, grantedAtMs: Long, expiresAtMs: Long? = null, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.driveRevokeShareJson(path: String, workspace: String, driveWorkspaceId: String, grantId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.driveApplyShareExpiryJson(path: String, workspace: String, driveWorkspaceId: String, nowMs: Long, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.drivePinRetentionJson(path: String, workspace: String, driveWorkspaceId: String, pinId: String, kind: String, root: String, targetEntityId: String? = null, addedAtMs: Long, expiresAtMs: Long? = null, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.driveUnpinRetentionJson(path: String, workspace: String, driveWorkspaceId: String, pinId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.driveApplyRetentionJson(path: String, workspace: String, driveWorkspaceId: String, nowMs: Long, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
