package ai.uldren.loom

expect fun Loom.spacesCreateJson(path: String, workspace: String, pageWorkspaceId: String, spaceId: String, title: String, expectedRoot: String? = null, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.spacesListJson(path: String, workspace: String, pageWorkspaceId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.spacesGetJson(path: String, workspace: String, pageWorkspaceId: String, spaceId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.pagesCreateJson(path: String, workspace: String, pageWorkspaceId: String, pageId: String, spaceId: String, parentPageId: String? = null, title: String, expectedRoot: String? = null, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.pagesUpdateJson(path: String, workspace: String, pageWorkspaceId: String, pageId: String, bodyText: String, expectedRoot: String? = null, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.pagesPublishJson(path: String, workspace: String, pageWorkspaceId: String, pageId: String, expectedRoot: String? = null, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.pagesGetJson(path: String, workspace: String, pageWorkspaceId: String, pageId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.pagesListJson(path: String, workspace: String, pageWorkspaceId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.pagesHistoryJson(path: String, workspace: String, pageWorkspaceId: String, pageId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.structuresCreateJson(path: String, workspace: String, pageWorkspaceId: String, structureId: String, spaceId: String, kind: String, title: String, expectedRoot: String? = null, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.structuresAddNodeJson(path: String, workspace: String, pageWorkspaceId: String, structureId: String, nodeId: String, kind: String, label: String, bodyDigest: String? = null, entityRef: String? = null, expectedRoot: String? = null, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.structuresUpdateNodeJson(path: String, workspace: String, pageWorkspaceId: String, structureId: String, nodeId: String, kind: String, label: String, bodyDigest: String? = null, entityRef: String? = null, expectedRoot: String? = null, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.structuresBindJson(path: String, workspace: String, pageWorkspaceId: String, structureId: String, nodeId: String, entityRef: String? = null, expectedRoot: String? = null, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.structuresMoveNodeJson(path: String, workspace: String, pageWorkspaceId: String, structureId: String, nodeId: String, parentNodeId: String? = null, label: String? = null, expectedRoot: String? = null, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.structuresLinkNodeJson(path: String, workspace: String, pageWorkspaceId: String, structureId: String, edgeId: String, srcNodeId: String, dstNodeId: String, label: String, targetRef: String? = null, expectedRoot: String? = null, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.structuresDecomposeToTicketsJson(path: String, workspace: String, pageWorkspaceId: String, structureId: String, itemsJson: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.structuresGetJson(path: String, workspace: String, pageWorkspaceId: String, structureId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.structuresListJson(path: String, workspace: String, pageWorkspaceId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
