package ai.uldren.loom

expect fun Loom.ticketsProjectCreateJson(path: String, workspace: String, ticketWorkspaceId: String, projectId: String, keyPrefix: String, name: String, expectedRoot: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.ticketsProjectRekeyJson(path: String, workspace: String, ticketWorkspaceId: String, projectId: String, keyPrefix: String, expectedRoot: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.ticketsProjectSettingsGetJson(path: String, workspace: String, ticketWorkspaceId: String, projectId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.ticketsProjectSettingsSetJson(path: String, workspace: String, ticketWorkspaceId: String, projectId: String, defaultProjection: String? = null, enableProjectionsJson: String = "[]", disableProjectionsJson: String = "[]", actorEnforcement: String? = null, projectOwnerPrincipal: String? = null, clearProjectOwnerPrincipal: Boolean = false, acceptanceAuthoritiesJson: String? = null, expectedRoot: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.ticketsFieldsJson(path: String, workspace: String, ticketWorkspaceId: String, projectId: String, projection: String = "native", operation: String = "create", passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.ticketsFieldPutJson(path: String, workspace: String, ticketWorkspaceId: String, projectId: String, fieldId: String, key: String, name: String, description: String? = null, fieldType: String = "string", optionSet: String? = null, maxLength: Int? = null, required: Boolean = false, searchable: Boolean = true, orderable: Boolean = false, cardinality: String = "optional", applicableTypeIdsJson: String = "[]", expectedRoot: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.ticketsFieldRetireJson(path: String, workspace: String, ticketWorkspaceId: String, projectId: String, fieldId: String, expectedRoot: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.ticketsCreateJson(path: String, workspace: String, ticketWorkspaceId: String, projectId: String, ticketType: String, externalSource: String? = null, externalId: String? = null, fieldsJson: String, policyLabelsJson: String = "[]", expectedRoot: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.ticketsUpdateJson(path: String, workspace: String, ticketWorkspaceId: String, ticketId: String, setFieldsJson: String = "{}", deleteFieldsJson: String = "[]", action: String? = null, targetStatus: String? = null, observedSourceStatus: String? = null, observedWorkflowVersion: String? = null, assignee: String? = null, expectedRoot: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null, commentId: String? = null, commentType: String? = null, commentBody: String? = null, commentsJson: String? = null, relationSetsJson: String? = null, relationRemovesJson: String? = null): String
expect fun Loom.ticketsDeleteJson(path: String, workspace: String, ticketWorkspaceId: String, ticketId: String, expectedRoot: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.ticketsRelationSetJson(path: String, workspace: String, ticketWorkspaceId: String, ticketId: String, relationId: String, kind: String, targetId: String, expectedRoot: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.ticketsRelationRemoveJson(path: String, workspace: String, ticketWorkspaceId: String, ticketId: String, relationId: String, expectedRoot: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.ticketsGetJson(path: String, workspace: String, ticketWorkspaceId: String, ticketId: String, projection: String = "native", passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.ticketsListJson(path: String, workspace: String, ticketWorkspaceId: String, projection: String = "native", passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
expect fun Loom.ticketsHistoryJson(path: String, workspace: String, ticketWorkspaceId: String, ticketId: String, passphrase: String? = null, kek: ByteArray? = null, authPrincipal: String? = null, authPassphrase: String? = null): String
