/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * An open SQL session over a workspace SQL facet in a `.loom`: run arbitrary SQL (results return as a JSON
 * array of result payloads) and commit the staged result. The whole versioned tabular + SQL stack
 * exposed to JavaScript; mirrors the C-ABI SQL session. In JS this is the `LoomSql` class.
 *
 * It is a reopenable handle, not a held lock: each `exec` / `commit` opens the `.loom` for the
 * duration of that call and releases it (matching the engine's single-writer / lock-free-reader model
 * and the `loom` CLI). So multiple `LoomSql` instances over the same file coexist and never deadlock.
 */
export declare class LoomSql {
  /**
   * Open `loomPath` and start a SQL session over workspace `nsName`'s SQL facet (created if absent),
   * database `db`.
   */
  constructor(loomPath: string, nsName: string, db: string)
  /**
   * Open an **encrypted** loom: same as the constructor but unlocks with
   * `passphrase`, held for the session's lifetime. In JS: `LoomSql.openEncrypted(path, ns, db, pass)`.
   * A wrong passphrase throws `E2E_KEY_INVALID`; opening an encrypted loom without one throws
   * `E2E_LOCKED`. The host acquires the passphrase securely; no environment variable is consulted.
   */
  static openEncrypted(loomPath: string, nsName: string, db: string, passphrase: string): LoomSql
  static authenticated(loomPath: string, nsName: string, db: string, authPrincipal: string, authPassphrase: string): LoomSql
  static openEncryptedAuthenticated(loomPath: string, nsName: string, db: string, passphrase: string, authPrincipal: string, authPassphrase: string): LoomSql
  /**
   * Run one or more `;`-separated SQL statements and return **typed** results: an array of statement
   * results, each a `{ kind, ... }` object. A `select` carries `columns` and `rows` of idiomatic
   * cells - `BigInt` for 64/128-bit integers, `number` for <=32-bit integers and floats, `Uint8Array`
   * for bytes, `string` for text, and `{ mantissa: BigInt, scale: number }` for an exact decimal.
   * Mutations are staged and persisted; call [`LoomSql::commit`] to record one. For the raw canonical
   * bytes use [`LoomSql::exec_bytes`]; for the JSON debug form use [`LoomSql::exec_json`].
   */
  exec(sql: string): unknown[]
  /**
   * Run SQL; returns a JSON array of the result payloads (debug/admin form, rendered from the
   * canonical CBOR - not the type-faithful API; use [`LoomSql::exec`]).
   */
  execJson(sql: string): string
  /** Run SQL; returns the result payloads as canonical CBOR bytes. */
  execBytes(sql: string): Uint8Array
  /**
   * Run a `SELECT` and return its rows as typed cell arrays (the streaming form). A JS
   * array is natively iterable, so `for (const row of db.query(sql))` walks the rows; each cell uses
   * the same idiomatic mapping as `exec`. Statements that mutate state are rejected.
   */
  query(sql: string): unknown[]
  /**
   * Run SQL asynchronously: the returned Promise resolves to the canonical-CBOR result bytes. The
   * blocking work runs on the libuv thread pool, off the JS event loop.
   */
  execAsync(sql: string): Promise<Uint8Array>
  /**
   * Commit the staged database state onto the workspace's current branch; returns the new commit's
   * content address (`"algo:hex"`).
   */
  commit(message: string, author: string): string
}

/**
 * An explicit transaction/batch scope: holds the `.loom` (and its write lock) open across statements,
 * so an SQL transaction (`BEGIN`/`COMMIT`/`ROLLBACK`) can span `exec` calls, and changes are made
 * durable by one atomic save at `commit`. Because JS GC is non-deterministic, call `close()` to release
 * the lock promptly (closing without a commit discards un-persisted changes). The SQL `COMMIT` is
 * distinct from the VCS `commitVcs`.
 */
export declare class LoomSqlBatch {
  /**
   * Begin a batch over workspace `nsName`'s SQL facet (created if absent), database `db`, in `loomPath`.
   * Holds the write lock until `close()`.
   */
  constructor(loomPath: string, nsName: string, db: string)
  /**
   * Begin a batch over an **encrypted** loom, unlocking with `passphrase` for the
   * batch's lifetime. In JS: `LoomSqlBatch.openEncrypted(path, ns, db, pass)`.
   */
  static openEncrypted(loomPath: string, nsName: string, db: string, passphrase: string): LoomSqlBatch
  static authenticated(loomPath: string, nsName: string, db: string, authPrincipal: string, authPassphrase: string): LoomSqlBatch
  static openEncryptedAuthenticated(loomPath: string, nsName: string, db: string, passphrase: string, authPrincipal: string, authPassphrase: string): LoomSqlBatch
  /**
   * Run SQL in the batch and return typed results (same shape as `LoomSql.exec`). Includes
   * `BEGIN`/`COMMIT`/`ROLLBACK`; changes accumulate until `commit`.
   */
  exec(sql: string): unknown[]
  /** Run SQL in the batch; returns the result payloads as canonical CBOR bytes. */
  execBytes(sql: string): Uint8Array
  /** Run SQL in the batch; returns the JSON debug form. */
  execJson(sql: string): string
  /**
   * Make the batch's changes durable with one atomic save (no history entry). Rejected while an SQL
   * transaction is open. The batch stays open.
   */
  commit(): void
  /**
   * Like `commit`, but also records a VCS commit; returns the commit's content address. Distinct from
   * a SQL `COMMIT`. Rejected while an SQL transaction is open.
   */
  commitVcs(message: string, author: string): string
  /**
   * Discard un-persisted in-memory changes (and any open SQL transaction), reloading from the last
   * durable state. The batch stays open.
   */
  abort(): void
  /** Release the write lock and free the batch. Closing without a commit discards un-persisted changes. */
  close(): void
}

export declare function aclGrant(loomPath: string, effect: number, subject: string, workspace: string | undefined | null, domain: string | undefined | null, rightsMask: number, passphrase?: string | undefined | null, authPrincipal?: string | undefined | null, authPassphrase?: string | undefined | null, predicateCel?: string | undefined | null): void

export declare function aclGrantScoped(loomPath: string, effect: number, subject: string, workspace: string | undefined | null, domain: string | undefined | null, rightsMask: number, refGlob?: string | undefined | null, scopes?: Array<string> | undefined | null, passphrase?: string | undefined | null, authPrincipal?: string | undefined | null, authPassphrase?: string | undefined | null, predicateCel?: string | undefined | null): void

export declare function aclListJson(loomPath: string, passphrase?: string | undefined | null, authPrincipal?: string | undefined | null, authPassphrase?: string | undefined | null): string

export declare function aclRevoke(loomPath: string, effect: number, subject: string, workspace: string | undefined | null, domain: string | undefined | null, rightsMask: number, passphrase?: string | undefined | null, authPrincipal?: string | undefined | null, authPassphrase?: string | undefined | null, predicateCel?: string | undefined | null): boolean

export declare function aclRevokeScoped(loomPath: string, effect: number, subject: string, workspace: string | undefined | null, domain: string | undefined | null, rightsMask: number, refGlob?: string | undefined | null, scopes?: Array<string> | undefined | null, passphrase?: string | undefined | null, authPrincipal?: string | undefined | null, authPassphrase?: string | undefined | null, predicateCel?: string | undefined | null): boolean

/** Append `content` to file `path`, creating it if absent (the parent directory must exist). */
export declare function appendFile(loomPath: string, facet: string, workspace: string, path: string, content: Uint8Array, passphrase?: string | undefined | null): void

export declare function archiveExport(loomPath: string, workspace: string, dstPath: string, kind: string, revision: string | undefined | null, dryRun: boolean, passphrase?: string | undefined | null): Uint8Array

export declare function archiveImport(loomPath: string, workspace: string, srcPath: string, kind: string, dryRun: boolean, passphrase?: string | undefined | null): Uint8Array

export declare function authenticatePassphrase(loomPath: string, principal: string, principalPassphrase: string, passphrase?: string | undefined | null): void

/** Compute the Blob content address (`"algo:hex"`) of the given bytes. */
export declare function blobDigest(data: Uint8Array): string

/**
 * Create (or replace the metadata of) calendar collection `collection` under `principal` in workspace
 * `workspace` (UUID or name, created with the `calendar` facet if absent). `displayName` is the
 * collection's display name; `components` is a comma-separated component set ("event,todo"; "" is the
 * empty set).
 */
export declare function calCreateCollection(loomPath: string, workspace: string, principal: string, collection: string, displayName: string, components: string, passphrase?: string | undefined | null): void

/**
 * Delete calendar collection `collection` under `principal` and every entry in it; returns whether it
 * existed.
 */
export declare function calDeleteCollection(loomPath: string, workspace: string, principal: string, collection: string, passphrase?: string | undefined | null): boolean

/** Remove the calendar entry at `uid` in collection `collection`; returns whether it was present. */
export declare function calDeleteEntry(loomPath: string, workspace: string, principal: string, collection: string, uid: string, passphrase?: string | undefined | null): boolean

/** The on-demand iCalendar (`.ics`) projection of the entry at `uid`, or `null` if absent. */
export declare function calEntryIcs(loomPath: string, workspace: string, principal: string, collection: string, uid: string, passphrase?: string | undefined | null): string | null

/**
 * Fetch the calendar entry at `uid` in collection `collection` as its `CalendarEntry` canonical CBOR, or
 * `null` if absent.
 */
export declare function calGetEntry(loomPath: string, workspace: string, principal: string, collection: string, uid: string, passphrase?: string | undefined | null): Uint8Array | null

/**
 * List the calendar collection ids under `principal` as the Loom Canonical CBOR array of text strings
 * (sorted; an absent principal is the empty array).
 */
export declare function calListCollections(loomPath: string, workspace: string, principal: string, passphrase?: string | undefined | null): Uint8Array

/**
 * List collection `collection` as the Loom Canonical CBOR array of per-entry `CalendarEntry` canonical
 * CBOR byte strings (UID order; an absent collection is the empty array).
 */
export declare function calListEntries(loomPath: string, workspace: string, principal: string, collection: string, passphrase?: string | undefined | null): Uint8Array

/**
 * Put the calendar `entry` (its `CalendarEntry` canonical CBOR) into the existing collection
 * `collection` under `principal`, keyed by its UID. A later put at the same UID replaces it.
 */
export declare function calPutEntry(loomPath: string, workspace: string, principal: string, collection: string, entry: Uint8Array, passphrase?: string | undefined | null): void

/**
 * Parse iCalendar document `ics` and store it as a record in collection `collection` (the validated
 * write-in path); returns the new ETag as a `"algo:hex"` string.
 */
export declare function calPutIcs(loomPath: string, workspace: string, principal: string, collection: string, ics: string, passphrase?: string | undefined | null): string

/**
 * Expand collection `collection` into occurrences within the half-open wall-clock window `[from, to)`
 * (both `YYYYMMDDTHHMMSS`). Returns the Loom Canonical CBOR array of `[uid, "YYYYMMDDTHHMMSS"]` pairs
 * (start order, then UID).
 */
export declare function calRange(loomPath: string, workspace: string, principal: string, collection: string, from: string, to: string, passphrase?: string | undefined | null): Uint8Array

/**
 * Search collection `collection` by component filter and substring. `component` is "" (any), "event", or
 * "todo"; `text` is a case-insensitive substring over the summary ("" matches any). Returns the Loom
 * Canonical CBOR array of per-entry `CalendarEntry` canonical CBOR byte strings (UID order).
 */
export declare function calSearch(loomPath: string, workspace: string, principal: string, collection: string, component: string, text: string, passphrase?: string | undefined | null): Uint8Array

/**
 * The build capability report (0010 section 5) as canonical CBOR: a `CapabilitySet` map with
 * `schema_version` and `records`. Build-aware: this binding links loom-store and loom-sql, so their
 * owned capabilities are reported with operational state `supported`. Mirrors the C ABI
 * `loom_capabilities`.
 */
export declare function capabilities(): Uint8Array

/**
 * Create (or replace the metadata of) address book `book` under `principal` in workspace `workspace`
 * (UUID or name, created with the `contacts` facet if absent). `displayName` is the book's display name.
 */
export declare function cardCreateBook(loomPath: string, workspace: string, principal: string, book: string, displayName: string, passphrase?: string | undefined | null): void

/** Delete address book `book` under `principal` and every contact in it; returns whether it existed. */
export declare function cardDeleteBook(loomPath: string, workspace: string, principal: string, book: string, passphrase?: string | undefined | null): boolean

/** Remove the contact at `uid` in address book `book`; returns whether it was present. */
export declare function cardDeleteEntry(loomPath: string, workspace: string, principal: string, book: string, uid: string, passphrase?: string | undefined | null): boolean

/** The on-demand vCard (`.vcf`) projection of the contact at `uid`, or `null` if absent. */
export declare function cardEntryVcard(loomPath: string, workspace: string, principal: string, book: string, uid: string, passphrase?: string | undefined | null): string | null

/**
 * Fetch the contact at `uid` in address book `book` as its `ContactEntry` canonical CBOR, or `null` if
 * absent.
 */
export declare function cardGetEntry(loomPath: string, workspace: string, principal: string, book: string, uid: string, passphrase?: string | undefined | null): Uint8Array | null

/**
 * List the address-book ids under `principal` as the Loom Canonical CBOR array of text strings (sorted;
 * an absent principal is the empty array).
 */
export declare function cardListBooks(loomPath: string, workspace: string, principal: string, passphrase?: string | undefined | null): Uint8Array

/**
 * List address book `book` as the Loom Canonical CBOR array of per-contact `ContactEntry` canonical CBOR
 * byte strings (UID order; an absent book is the empty array).
 */
export declare function cardListEntries(loomPath: string, workspace: string, principal: string, book: string, passphrase?: string | undefined | null): Uint8Array

/**
 * Put the contact `entry` (its `ContactEntry` canonical CBOR) into the existing address book `book` under
 * `principal`, keyed by its UID. A later put at the same UID replaces it.
 */
export declare function cardPutEntry(loomPath: string, workspace: string, principal: string, book: string, entry: Uint8Array, passphrase?: string | undefined | null): void

/**
 * Parse vCard document `vcf` and store it as a record in address book `book` (the validated write-in
 * path); returns the new ETag as a `"algo:hex"` string.
 */
export declare function cardPutVcard(loomPath: string, workspace: string, principal: string, book: string, vcf: string, passphrase?: string | undefined | null): string

/**
 * Search address book `book` by a case-insensitive substring `text` over the formatted name,
 * organization, and email values. Returns the Loom Canonical CBOR array of per-contact `ContactEntry`
 * canonical CBOR byte strings (UID order).
 */
export declare function cardSearch(loomPath: string, workspace: string, principal: string, book: string, text: string, passphrase?: string | undefined | null): Uint8Array

export declare function carExport(loomPath: string, workspace: string, dstPath: string, dryRun: boolean, passphrase?: string | undefined | null): Uint8Array

export declare function carImport(loomPath: string, srcPath: string, dryRun: boolean, passphrase?: string | undefined | null): Uint8Array

/**
 * Drop the blob addressed by `digest` from a workspace's working tree, making it unreachable going
 * forward; returns whether it was present. CAS stays immutable: the bytes are reclaimed by GC once
 * unreferenced, and an earlier commit that held the blob still restores it.
 */
export declare function casDelete(loomPath: string, workspace: string, digest: string, passphrase?: string | undefined | null): boolean

/**
 * Fetch the blob addressed by `digest` from a workspace, or `null` if absent. An invalid digest throws
 * `INVALID_ARGUMENT`; a content/digest mismatch throws `INTEGRITY_FAILURE`.
 */
export declare function casGet(loomPath: string, workspace: string, digest: string, passphrase?: string | undefined | null): Uint8Array | null

/**
 * Whether a blob addressed by `digest` is present in a workspace. An invalid digest throws
 * `INVALID_ARGUMENT`.
 */
export declare function casHas(loomPath: string, workspace: string, digest: string, passphrase?: string | undefined | null): boolean

/**
 * List the content addresses (`"algo:hex"`) reachable in a workspace's `cas` facet as a JSON string
 * array, sorted. Enumeration is within the workspace, not a global index.
 */
export declare function casListJson(loomPath: string, workspace: string, passphrase?: string | undefined | null): string

/**
 * Store bytes in the `cas` facet of a workspace (by UUID or name, created if absent); returns the
 * content address (`"algo:hex"`). Idempotent: identical bytes yield the same address.
 */
export declare function casPut(loomPath: string, workspace: string, content: Uint8Array, passphrase?: string | undefined | null): string

/**
 * Cherry-pick `commits` (digest strings) onto the current branch, preserving each author and message.
 * `dryRun` previews conflicts. Returns the outcome JSON.
 */
export declare function cherryPick(loomPath: string, facet: string, workspace: string, commits: Array<string>, dryRun: boolean, passphrase?: string | undefined | null): string

/** Evaluate aggregate expressions from CBOR `[[op, column?] ...]`, with optional select filter. */
export declare function columnarAggregate(loomPath: string, workspace: string, name: string, aggregates: Uint8Array, filter: Uint8Array, passphrase?: string | undefined | null): Uint8Array

/**
 * Append `row` (a CBOR cell array) to dataset `name`, validating arity + column types. `NOT_FOUND` if
 * the dataset was never created; `INVALID_ARGUMENT` on an arity or type mismatch.
 */
export declare function columnarAppend(loomPath: string, workspace: string, name: string, row: Uint8Array, passphrase?: string | undefined | null): void

/**
 * The `(name, type_tag)` columns of dataset `name` as the Loom Canonical CBOR array of `[name,
 * type_tag]`. `NOT_FOUND` if the dataset does not exist.
 */
export declare function columnarColumns(loomPath: string, workspace: string, name: string, passphrase?: string | undefined | null): Uint8Array

/** Compact dataset `name` at its target segment size. */
export declare function columnarCompact(loomPath: string, workspace: string, name: string, passphrase?: string | undefined | null): void

/**
 * Create columnar dataset `name` with `columns` (a CBOR array of `[name, type_tag]`) and
 * `targetSegmentRows` (0 for the engine default) in workspace `workspace` (UUID or name, created with
 * the `columnar` facet if absent). `CONFLICT` if the dataset already exists.
 */
export declare function columnarCreate(loomPath: string, workspace: string, name: string, columns: Uint8Array, targetSegmentRows: bigint, passphrase?: string | undefined | null): void

/** Inspect dataset metadata as CBOR `[columns, rows, segment_count, target_segment_rows, source_digest]`. */
export declare function columnarInspect(loomPath: string, workspace: string, name: string, passphrase?: string | undefined | null): Uint8Array

/** The total row count of dataset `name`. `NOT_FOUND` if the dataset does not exist. */
export declare function columnarRows(loomPath: string, workspace: string, name: string, passphrase?: string | undefined | null): bigint

/**
 * All rows of dataset `name` in append order as the Loom Canonical CBOR array of cell arrays.
 * `NOT_FOUND` if the dataset does not exist.
 */
export declare function columnarScan(loomPath: string, workspace: string, name: string, passphrase?: string | undefined | null): Uint8Array

/**
 * Project `columns` (a CBOR array of text) from dataset `name`'s rows matching `filter` as the Loom
 * Canonical CBOR array of cell arrays. The filter is the CBOR array `[column, op, value_cell]` (op: 0
 * eq, 1 ne, 2 lt, 3 le, 4 gt, 5 ge); an empty filter buffer scans every row. `NOT_FOUND` if the dataset
 * does not exist; `INVALID_ARGUMENT` on an unknown column.
 */
export declare function columnarSelect(loomPath: string, workspace: string, name: string, columns: Uint8Array, filter: Uint8Array, passphrase?: string | undefined | null): Uint8Array

/** Source digest used by derived columnar projections as CBOR text. */
export declare function columnarSourceDigest(loomPath: string, workspace: string, name: string, passphrase?: string | undefined | null): Uint8Array

/** Commit only the staged index (`commit --staged`); returns the new commit's content address. */
export declare function commitStaged(loomPath: string, facet: string, workspace: string, author: string, message: string, passphrase?: string | undefined | null): string

/**
 * Create a fresh `.loom` under an identity profile, optionally encrypted - the JS counterpart of
 * `loom init [--identity-profile fips] [--encrypt]`. `profile` is
 * `"default"`/`"blake3"` or `"fips"`/`"sha256"`; a null/empty `passphrase` makes an unencrypted store,
 * otherwise the DEK is wrapped under it (Argon2id) with `suite` (or the profile default) as the AEAD.
 * Throws `ALREADY_EXISTS` if a non-empty file is already there.
 */
export declare function createLoom(path: string, profile: string, suite?: string | undefined | null, passphrase?: string | undefined | null): void

/** Add or remove a long-lived pin on a running local daemon. */
export declare function daemonPinAdd(loomPath: string, pin: string): void

export declare function daemonPinRemove(loomPath: string, pin: string): void

/** Attach or detach a named session from a running local daemon. */
export declare function daemonSessionAttach(loomPath: string, session: string): void

export declare function daemonSessionDetach(loomPath: string, session: string): void

/** Local daemon status for `loomPath` as JSON. Missing daemons return a STOPPED JSON payload. */
export declare function daemonStatusJson(loomPath: string): string

/** Execute dataframe frame `name` and return canonical CBOR `[columns, rows]`. */
export declare function dataframeCollect(loomPath: string, workspace: string, name: string, passphrase?: string | undefined | null): Uint8Array

/** Create dataframe frame `name` from canonical DataframePlan CBOR. */
export declare function dataframeCreate(loomPath: string, workspace: string, name: string, plan: Uint8Array, passphrase?: string | undefined | null): void

/** Materialize dataframe frame `name`; returns a CAS digest when the materialization target emits one. */
export declare function dataframeMaterialize(loomPath: string, workspace: string, name: string, passphrase?: string | undefined | null): string | null

/** Canonical dataframe plan digest as `algo:hex`. */
export declare function dataframePlanDigest(loomPath: string, workspace: string, name: string, passphrase?: string | undefined | null): string

/** Execute dataframe frame `name` and return at most `rows` rows as canonical CBOR `[columns, rows]`. */
export declare function dataframePreview(loomPath: string, workspace: string, name: string, rows: bigint, passphrase?: string | undefined | null): Uint8Array

/** Source digests pinned in the dataframe plan as canonical CBOR array of `algo:hex` strings. */
export declare function dataframeSourceDigests(loomPath: string, workspace: string, name: string, passphrase?: string | undefined | null): Uint8Array

export interface DocBinary {
  bytes: Uint8Array
  digest: string
  entityTag: string
}

/** Remove `id` from collection `collection`; returns whether it was present. */
export declare function docDelete(loomPath: string, workspace: string, collection: string, id: string, passphrase?: string | undefined | null): boolean

export declare function docFindJson(loomPath: string, workspace: string, collection: string, index: string, valueJson: string, passphrase?: string | undefined | null): string

/** Fetch `id` as binary bytes with its content digest, or `null` if absent. */
export declare function docGetBinary(loomPath: string, workspace: string, collection: string, id: string, passphrase?: string | undefined | null): DocBinary | null

/** Fetch `id` as UTF-8 text with its content digest, or `null` if absent. */
export declare function docGetText(loomPath: string, workspace: string, collection: string, id: string, passphrase?: string | undefined | null): DocText | null

export declare function docIndexCreate(loomPath: string, workspace: string, collection: string, name: string, fieldPath: string, unique: boolean, passphrase?: string | undefined | null): void

export declare function docIndexCreateJson(loomPath: string, workspace: string, collection: string, declarationJson: Uint8Array, passphrase?: string | undefined | null): void

export declare function docIndexDrop(loomPath: string, workspace: string, collection: string, name: string, passphrase?: string | undefined | null): boolean

export declare function docIndexListJson(loomPath: string, workspace: string, collection: string, passphrase?: string | undefined | null): string

export declare function docIndexRebuild(loomPath: string, workspace: string, collection: string, name: string, passphrase?: string | undefined | null): void

export declare function docIndexStatusJson(loomPath: string, workspace: string, collection: string, passphrase?: string | undefined | null): string

/** List collection `collection` as its canonical binary representation. */
export declare function docListBinary(loomPath: string, workspace: string, collection: string, passphrase?: string | undefined | null): Uint8Array

export interface DocPutResult { digest: string, entityTag: string }

/** Put binary bytes at string `id` in collection `collection` and return the new document tags. */
export declare function docPutBinary(loomPath: string, workspace: string, collection: string, id: string, bytes: Uint8Array, expectedEntityTag?: string | undefined | null, passphrase?: string | undefined | null): DocPutResult

/** Put UTF-8 text at string `id` in collection `collection` and return the new document tags. */
export declare function docPutText(loomPath: string, workspace: string, collection: string, id: string, text: string, expectedEntityTag?: string | undefined | null, passphrase?: string | undefined | null): DocPutResult

export declare function docQueryJson(loomPath: string, workspace: string, collection: string, queryJson: string, passphrase?: string | undefined | null): string

export interface DocText {
  text: string
  digest: string
  entityTag: string
}

/** Execute a canonical `loom.exec.request.v1` request and return canonical `loom.exec.result.v1`. */
export declare function execCbor(loomPath: string, request: Uint8Array, passphrase?: string | undefined | null): Uint8Array

/** Close handle `file`, releasing it (delete-on-last-close for an unlinked inode). */
export declare function fileClose(loomPath: string, file: number, passphrase?: string | undefined | null): void

/** Flush handle `file` (validates the handle; writes already apply per operation). */
export declare function fileFlush(loomPath: string, file: number, passphrase?: string | undefined | null): void

/**
 * Open a file handle on `path` with `mode` (`read`|`write`|`read_write`|`append`), returning the handle
 * id (valid until `fileClose`).
 */
export declare function fileOpen(loomPath: string, facet: string, workspace: string, path: string, mode: string, passphrase?: string | undefined | null): number

/** Sequentially read up to `len` bytes from handle `file` at its cursor, advancing it. */
export declare function fileRead(loomPath: string, file: number, len: number, passphrase?: string | undefined | null): Uint8Array

/** Positionally read up to `len` bytes at `offset` from handle `file` without moving its cursor. */
export declare function fileReadAt(loomPath: string, file: number, offset: number, len: number, passphrase?: string | undefined | null): Uint8Array

/** The live size and mode of handle `file`. */
export declare function fileStat(loomPath: string, file: number, passphrase?: string | undefined | null): FileStatJs

/** The live size and mode of an open file handle. */
export interface FileStatJs {
  /** Live byte length. */
  size: number
  /** POSIX-style mode bits. */
  mode: number
}

/** Resize handle `file` to `size` bytes. */
export declare function fileTruncate(loomPath: string, file: number, size: number, passphrase?: string | undefined | null): void

/**
 * Sequentially write `content` to handle `file` at its cursor (or end of file for an append handle),
 * advancing it; returns the byte count.
 */
export declare function fileWrite(loomPath: string, file: number, content: Uint8Array, passphrase?: string | undefined | null): number

/**
 * Positionally write `content` at `offset` of handle `file` without moving its cursor; returns the byte
 * count.
 */
export declare function fileWriteAt(loomPath: string, file: number, offset: number, content: Uint8Array, passphrase?: string | undefined | null): number

export declare function fsExport(loomPath: string, workspace: string, dstPath: string, revision: string | undefined | null, dryRun: boolean, passphrase?: string | undefined | null): Uint8Array

export declare function fsImport(loomPath: string, workspace: string, srcPath: string, commit: boolean, dryRun: boolean, passphrase?: string | undefined | null): Uint8Array

export declare function graphExplainQuery(loomPath: string, workspace: string, name: string, query: string, passphrase?: string | undefined | null): Uint8Array

/**
 * Fetch edge `id` in graph `name` as the CBOR array `[src, dst, label, props]`, or `null` if the edge or
 * graph is absent.
 */
export declare function graphGetEdge(loomPath: string, workspace: string, name: string, id: string, passphrase?: string | undefined | null): Uint8Array | null

/**
 * Fetch node `id`'s properties in graph `name` as a CBOR `text -> scalar` map, or `null` if the node or
 * graph is absent.
 */
export declare function graphGetNode(loomPath: string, workspace: string, name: string, id: string, passphrase?: string | undefined | null): Uint8Array | null

/**
 * In-edges of `id` in graph `name` as the Loom Canonical CBOR array of `[edge_id, [src, dst, label,
 * props]]` in edge-id order.
 */
export declare function graphInEdges(loomPath: string, workspace: string, name: string, id: string, passphrase?: string | undefined | null): Uint8Array

/**
 * The distinct adjacent node ids of `id` in graph `name`, sorted, as the Loom Canonical CBOR array of
 * text (empty when the node or graph is absent).
 */
export declare function graphNeighbors(loomPath: string, workspace: string, name: string, id: string, passphrase?: string | undefined | null): Uint8Array

/**
 * Out-edges of `id` in graph `name` as the Loom Canonical CBOR array of `[edge_id, [src, dst, label,
 * props]]` in edge-id order.
 */
export declare function graphOutEdges(loomPath: string, workspace: string, name: string, id: string, passphrase?: string | undefined | null): Uint8Array

export declare function graphQuery(loomPath: string, workspace: string, name: string, query: string, passphrase?: string | undefined | null): Uint8Array

/**
 * Node ids reachable from `start` in graph `name` as the Loom Canonical CBOR array of text.
 * `maxDepth < 0` is no limit; `viaLabel` empty follows every edge, else only edges with that label.
 */
export declare function graphReachable(loomPath: string, workspace: string, name: string, start: string, maxDepth: number, viaLabel: string, passphrase?: string | undefined | null): Uint8Array

/** Remove edge `id` from graph `name`; returns whether it was present. An absent edge or graph is a no-op. */
export declare function graphRemoveEdge(loomPath: string, workspace: string, name: string, id: string, passphrase?: string | undefined | null): boolean

/**
 * Remove node `id` from graph `name`. `cascade=0` rejects with `CONFLICT` while incident edges exist;
 * `cascade!=0` removes the node and its incident edges. `NOT_FOUND` if the node is absent.
 */
export declare function graphRemoveNode(loomPath: string, workspace: string, name: string, id: string, cascade: number, passphrase?: string | undefined | null): void

/**
 * A shortest directed path from `from` to `to` in graph `name` as the Loom Canonical CBOR array of
 * node-id text, or `null` if no path exists (or an endpoint or the graph is absent). `viaLabel` empty
 * follows every edge, else only edges with that label.
 */
export declare function graphShortestPath(loomPath: string, workspace: string, name: string, from: string, to: string, viaLabel: string, passphrase?: string | undefined | null): Uint8Array | null

/**
 * Insert or replace edge `id` from `src` to `dst` (both endpoints must already exist, else `NOT_FOUND`)
 * with `label` and `props` (CBOR `text -> scalar` map, or empty) in graph `name`.
 */
export declare function graphUpsertEdge(loomPath: string, workspace: string, name: string, id: string, src: string, dst: string, label: string, props: Uint8Array, passphrase?: string | undefined | null): void

/**
 * Insert or replace node `id` (with `props` as a CBOR `text -> scalar` map, or empty for none) in graph
 * `name` of workspace `workspace` (UUID or name, created with the `graph` facet if absent).
 */
export declare function graphUpsertNode(loomPath: string, workspace: string, name: string, id: string, props: Uint8Array, passphrase?: string | undefined | null): void

export declare function identityAddPrincipal(loomPath: string, principalHandle: string, name: string, kind: string, passphrase?: string | undefined | null, authPrincipal?: string | undefined | null, authPassphrase?: string | undefined | null): string

export declare function identityAddPublicKey(loomPath: string, principal: string, label: string, algorithm: string, publicKeyHex: string, passphrase?: string | undefined | null, authPrincipal?: string | undefined | null, authPassphrase?: string | undefined | null): string

export declare function identityAssignRole(loomPath: string, principal: string, role: string, passphrase?: string | undefined | null, authPrincipal?: string | undefined | null, authPassphrase?: string | undefined | null): void

export declare function identityCreateExternalCredential(loomPath: string, principal: string, kind: string, label: string, issuer: string, subject: string, materialDigest?: string | undefined | null, passphrase?: string | undefined | null, authPrincipal?: string | undefined | null, authPassphrase?: string | undefined | null): string

export declare function identityListJson(loomPath: string, passphrase?: string | undefined | null, authPrincipal?: string | undefined | null, authPassphrase?: string | undefined | null): string

export declare function identityRemovePrincipal(loomPath: string, principal: string, passphrase?: string | undefined | null, authPrincipal?: string | undefined | null, authPassphrase?: string | undefined | null): void

export declare function identityRenamePrincipalHandle(loomPath: string, principal: string, principalHandle: string, passphrase?: string | undefined | null, authPrincipal?: string | undefined | null, authPassphrase?: string | undefined | null): void

export declare function identityRevokeExternalCredential(loomPath: string, credential: string, passphrase?: string | undefined | null, authPrincipal?: string | undefined | null, authPassphrase?: string | undefined | null): void

export declare function identityRevokePublicKey(loomPath: string, key: string, passphrase?: string | undefined | null, authPrincipal?: string | undefined | null, authPassphrase?: string | undefined | null): void

export declare function identityRevokeRole(loomPath: string, principal: string, role: string, passphrase?: string | undefined | null, authPrincipal?: string | undefined | null, authPassphrase?: string | undefined | null): boolean

export declare function identitySetPassphrase(loomPath: string, principal: string, principalPassphrase: string, passphrase?: string | undefined | null, authPrincipal?: string | undefined | null, authPassphrase?: string | undefined | null): void

/**
 * Add a passphrase unlock wrap to an encrypted store, unlocking it with the existing `passphrase`.
 * `allowNoRecovery` permits leaving no passphrase recovery wrap. The host supplies both secrets; no
 * environment variable is read.
 */
export declare function keyAddWrapKeyed(loomPath: string, passphrase: string, newPassphrase: string, allowNoRecovery: boolean): void

/**
 * Add a host-supplied 256-bit raw-KEK unlock wrap to an encrypted store, unlocking it with
 * `passphrase`. The host acquires the 32-byte KEK securely (keychain, Secure Enclave, passkey PRF,
 * KMS); Loom receives only the bytes.
 */
export declare function keyAddWrapWithKek(loomPath: string, passphrase: string, kek: Uint8Array, allowNoRecovery: boolean): void

/**
 * Remove one unlock wrap by zero-based `index` from an encrypted store, unlocking it with
 * `passphrase`. `allowNoRecovery` permits removing the last passphrase recovery wrap.
 */
export declare function keyRemoveWrap(loomPath: string, passphrase: string, index: number, allowNoRecovery: boolean): void

/** Remove typed `key` from map `collection` of `workspace`; returns whether it was present. */
export declare function kvDelete(loomPath: string, workspace: string, collection: string, key: Uint8Array, passphrase?: string | undefined | null): boolean

/** Fetch the value at typed `key` in map `collection` of `workspace`, or `null` if the key or map is absent. */
export declare function kvGet(loomPath: string, workspace: string, collection: string, key: Uint8Array, passphrase?: string | undefined | null): Uint8Array | null

/**
 * List map `collection` of `workspace` as the Loom Canonical CBOR array of `[key, value]` pairs in key order
 * (an absent map is the empty array).
 */
export declare function kvList(loomPath: string, workspace: string, collection: string, passphrase?: string | undefined | null): Uint8Array

/**
 * Put `value` at the typed `key` (Loom Canonical CBOR cell) in map `collection` of `workspace` (UUID or name,
 * created with the `kv` facet if absent). A later put at the same key replaces the value.
 */
export declare function kvPut(loomPath: string, workspace: string, collection: string, key: Uint8Array, value: Uint8Array, passphrase?: string | undefined | null): void

/**
 * The entries of map `collection` with `lo <= key < hi` (half-open, key order) as the Loom Canonical CBOR
 * array of `[key, value]` pairs. `lo`/`hi` are typed-cell CBOR keys.
 */
export declare function kvRange(loomPath: string, workspace: string, collection: string, lo: Uint8Array, hi: Uint8Array, passphrase?: string | undefined | null): Uint8Array

export declare function lanesCreate(loomPath: string, workspace: string, lane: Uint8Array, passphrase?: string | undefined | null): Uint8Array

export declare function lanesDelete(loomPath: string, workspace: string, laneId: string, updatedBy: string, passphrase?: string | undefined | null): Uint8Array

export declare function lanesGet(loomPath: string, workspace: string, laneId: string, passphrase?: string | undefined | null): Uint8Array | null

export declare function lanesList(loomPath: string, workspace: string, passphrase?: string | undefined | null): Uint8Array

export declare function lanesReviewerFeedbackUpdate(loomPath: string, workspace: string, laneId: string, reviewerFeedback: string, updatedBy: string, passphrase?: string | undefined | null): Uint8Array

export declare function lanesStatusReportUpdate(loomPath: string, workspace: string, laneId: string, statusReport: string, updatedBy: string, passphrase?: string | undefined | null): Uint8Array

export declare function lanesDeleteClosed(loomPath: string, workspace: string, laneId: string, updatedBy: string, passphrase?: string | undefined | null): Uint8Array

export declare function lanesTicketAdd(loomPath: string, workspace: string, laneId: string, ticketId: string, updatedBy: string, placement: string, anchor?: string | undefined | null, passphrase?: string | undefined | null): Uint8Array

export declare function lanesTicketRemove(loomPath: string, workspace: string, laneId: string, ticketId: string, updatedBy: string, passphrase?: string | undefined | null): Uint8Array

export declare function lanesTicketTransfer(loomPath: string, workspace: string, sourceLaneId: string, targetLaneId: string, ticketId: string, updatedBy: string, passphrase?: string | undefined | null): Uint8Array

export declare function spacesCreateJson(loomPath: string, workspace: string, pageWorkspaceId: string, spaceId: string, title: string, expectedRoot?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function spacesListJson(loomPath: string, workspace: string, pageWorkspaceId: string, passphrase?: string | undefined | null): string

export declare function spacesGetJson(loomPath: string, workspace: string, pageWorkspaceId: string, spaceId: string, passphrase?: string | undefined | null): string

export declare function pagesCreateJson(loomPath: string, workspace: string, pageWorkspaceId: string, pageId: string, spaceId: string, parentPageId: string | undefined | null, title: string, expectedRoot?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function pagesUpdateJson(loomPath: string, workspace: string, pageWorkspaceId: string, pageId: string, bodyText: string, expectedRoot?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function pagesPublishJson(loomPath: string, workspace: string, pageWorkspaceId: string, pageId: string, expectedRoot?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function pagesGetJson(loomPath: string, workspace: string, pageWorkspaceId: string, pageId: string, passphrase?: string | undefined | null): string

export declare function pagesListJson(loomPath: string, workspace: string, pageWorkspaceId: string, passphrase?: string | undefined | null): string

export declare function pagesHistoryJson(loomPath: string, workspace: string, pageWorkspaceId: string, pageId: string, passphrase?: string | undefined | null): string

export declare function structuresCreateJson(loomPath: string, workspace: string, pageWorkspaceId: string, structureId: string, spaceId: string, kind: string, title: string, expectedRoot?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function structuresAddNodeJson(loomPath: string, workspace: string, pageWorkspaceId: string, structureId: string, nodeId: string, kind: string, label: string, bodyDigest?: string | undefined | null, entityRef?: string | undefined | null, expectedRoot?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function structuresUpdateNodeJson(loomPath: string, workspace: string, pageWorkspaceId: string, structureId: string, nodeId: string, kind: string, label: string, bodyDigest?: string | undefined | null, entityRef?: string | undefined | null, expectedRoot?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function structuresBindJson(loomPath: string, workspace: string, pageWorkspaceId: string, structureId: string, nodeId: string, entityRef?: string | undefined | null, expectedRoot?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function structuresMoveNodeJson(loomPath: string, workspace: string, pageWorkspaceId: string, structureId: string, nodeId: string, parentNodeId?: string | undefined | null, label?: string | undefined | null, expectedRoot?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function structuresLinkNodeJson(loomPath: string, workspace: string, pageWorkspaceId: string, structureId: string, edgeId: string, srcNodeId: string, dstNodeId: string, label: string, targetRef?: string | undefined | null, expectedRoot?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function structuresDecomposeToTicketsJson(loomPath: string, workspace: string, pageWorkspaceId: string, structureId: string, itemsJson: string, passphrase?: string | undefined | null): string

export declare function structuresGetJson(loomPath: string, workspace: string, pageWorkspaceId: string, structureId: string, passphrase?: string | undefined | null): string

export declare function structuresListJson(loomPath: string, workspace: string, pageWorkspaceId: string, passphrase?: string | undefined | null): string

/**
 * Append `payload` to ledger `collection` of `workspace` (created with the `ledger` facet if absent); returns
 * the new zero-based sequence.
 */
export declare function ledgerAppend(loomPath: string, workspace: string, collection: string, payload: Uint8Array, passphrase?: string | undefined | null): bigint

/** The payload at `seq` in ledger `collection`, or `null` if absent. */
export declare function ledgerGet(loomPath: string, workspace: string, collection: string, seq: bigint, passphrase?: string | undefined | null): Uint8Array | null

/** The head chain hash (32 bytes) of ledger `collection`, or `null` when absent or empty. */
export declare function ledgerHead(loomPath: string, workspace: string, collection: string, passphrase?: string | undefined | null): Uint8Array | null

/** The number of entries in ledger `collection` (0 when absent). */
export declare function ledgerLen(loomPath: string, workspace: string, collection: string, passphrase?: string | undefined | null): bigint

/** Recompute and verify ledger `collection`'s hash chain; an altered payload or broken link is an error. */
export declare function ledgerVerify(loomPath: string, workspace: string, collection: string, passphrase?: string | undefined | null): void

/** Acquire, refresh, or release a daemon-backed lock. Token-returning calls return JSON. */
export declare function lockAcquireJson(loomPath: string, key: string, principal: string, session: string, mode: string, permits: number, capacity: number, leaseMs: bigint, waitMs?: bigint | undefined | null): string

export declare function lockRefreshJson(loomPath: string, key: string, principal: string, session: string, mode: string, permits: number, capacity: number, fenceLow: bigint, fenceHigh: bigint, leaseMs: bigint): string

export declare function lockRelease(loomPath: string, key: string, principal: string, session: string, mode: string, permits: number, capacity: number, fenceLow: bigint, fenceHigh: bigint): void

export declare function logsGetRecord(loomPath: string, workspace: string, recordId: string, passphrase?: string | undefined | null): Uint8Array | null

export declare function logsPutRecord(loomPath: string, workspace: string, record: Uint8Array, passphrase?: string | undefined | null): string

export declare function logsQuery(loomPath: string, workspace: string, fromTimeUnixNano: bigint, toTimeUnixNano: bigint, maxRecords: number, maxOutputBytes: bigint, passphrase?: string | undefined | null): Uint8Array

/**
 * Create (or replace the metadata of) mailbox `mailbox` under `principal` in workspace `workspace` (UUID
 * or name, created with the `mail` facet if absent). `displayName` is the mailbox's display name.
 */
export declare function mailCreateMailbox(loomPath: string, workspace: string, principal: string, mailbox: string, displayName: string, passphrase?: string | undefined | null): void

/**
 * Delete mailbox `mailbox` under `principal` and every message index and flag set in it (immutable
 * bodies stay in the CAS until GC); returns whether it existed.
 */
export declare function mailDeleteMailbox(loomPath: string, workspace: string, principal: string, mailbox: string, passphrase?: string | undefined | null): boolean

/**
 * Remove the message index and its flags at `uid` (the immutable body stays in the CAS until GC); returns
 * whether it was present.
 */
export declare function mailDeleteMessage(loomPath: string, workspace: string, principal: string, mailbox: string, uid: string, passphrase?: string | undefined | null): boolean

/**
 * The flags/labels on the message at `uid` as the Loom Canonical CBOR array of text strings (sorted,
 * deduplicated; an absent flag set is the empty array).
 */
export declare function mailGetFlags(loomPath: string, workspace: string, principal: string, mailbox: string, uid: string, passphrase?: string | undefined | null): Uint8Array

/**
 * Fetch the structured index of the message at `uid` in mailbox `mailbox` as its `MailMessage` canonical
 * CBOR, or `null` if absent.
 */
export declare function mailGetMessage(loomPath: string, workspace: string, principal: string, mailbox: string, uid: string, passphrase?: string | undefined | null): Uint8Array | null

/**
 * Ingest the raw RFC 5322 message `raw` into mailbox `mailbox` under `uid`: store the immutable body in
 * the CAS, parse the headers into a structured index, and write it. Returns the body's content address as
 * a `"algo:hex"` string.
 */
export declare function mailIngestMessage(loomPath: string, workspace: string, principal: string, mailbox: string, uid: string, raw: Uint8Array, passphrase?: string | undefined | null): string

/**
 * List the mailbox ids under `principal` as the Loom Canonical CBOR array of text strings (sorted; an
 * absent principal is the empty array).
 */
export declare function mailListMailboxes(loomPath: string, workspace: string, principal: string, passphrase?: string | undefined | null): Uint8Array

/**
 * List mailbox `mailbox` as the Loom Canonical CBOR array of per-message `MailMessage` canonical CBOR
 * byte strings (UID order; an absent mailbox is the empty array).
 */
export declare function mailListMessages(loomPath: string, workspace: string, principal: string, mailbox: string, passphrase?: string | undefined | null): Uint8Array

/**
 * Search mailbox `mailbox` by a case-insensitive substring `text` over the subject and from values.
 * Returns the Loom Canonical CBOR array of per-message `MailMessage` canonical CBOR byte strings (UID
 * order).
 */
export declare function mailSearch(loomPath: string, workspace: string, principal: string, mailbox: string, text: string, passphrase?: string | undefined | null): Uint8Array

/**
 * Replace the flags/labels on the message at `uid` with `flags`, a Loom Canonical CBOR `Array(Text)`
 * buffer. The message must exist.
 */
export declare function mailSetFlags(loomPath: string, workspace: string, principal: string, mailbox: string, uid: string, flags: Uint8Array, passphrase?: string | undefined | null): void

/**
 * Fetch the raw RFC 5322 body (`.eml` bytes) of the message at `uid`, from the CAS and digest-verified,
 * or `null` if absent.
 */
export declare function mailToEml(loomPath: string, workspace: string, principal: string, mailbox: string, uid: string, passphrase?: string | undefined | null): Uint8Array | null

export declare function meetingsImportSnapshot(loomPath: string, workspace: string, inputProfile: string, snapshot: Uint8Array, dryRun: boolean, passphrase?: string | undefined | null): string

export declare function meetingsSourceRead(loomPath: string, workspace: string, sourceId: string, leaf: string, passphrase?: string | undefined | null): Uint8Array

export declare function driveListJson(loomPath: string, workspace: string, driveWorkspaceId: string, folderId: string, passphrase?: string | undefined | null): string

export declare function driveStatJson(loomPath: string, workspace: string, driveWorkspaceId: string, folderId: string, name: string, passphrase?: string | undefined | null): string

export declare function driveReadFile(loomPath: string, workspace: string, driveWorkspaceId: string, fileId: string, passphrase?: string | undefined | null): Uint8Array

export declare function driveListVersionsJson(loomPath: string, workspace: string, driveWorkspaceId: string, fileId: string, passphrase?: string | undefined | null): string

export declare function driveListConflictsJson(loomPath: string, workspace: string, driveWorkspaceId: string, passphrase?: string | undefined | null): string

export declare function driveListSharesJson(loomPath: string, workspace: string, driveWorkspaceId: string, passphrase?: string | undefined | null): string

export declare function driveListRetentionJson(loomPath: string, workspace: string, driveWorkspaceId: string, passphrase?: string | undefined | null): string

export declare function driveCreateFolderJson(loomPath: string, workspace: string, driveWorkspaceId: string, parentFolderId: string, folderId: string, name: string, expectedRoot: string, passphrase?: string | undefined | null): string

export declare function driveCreateUploadJson(loomPath: string, workspace: string, driveWorkspaceId: string, uploadId: string, parentFolderId: string, name: string, fileId: string, expectedRoot: string, createdAtMs: bigint, replaceFile: boolean, passphrase?: string | undefined | null): string

export declare function driveUploadChunkJson(loomPath: string, workspace: string, driveWorkspaceId: string, uploadId: string, chunk: Uint8Array, passphrase?: string | undefined | null): string

export declare function driveCommitUploadJson(loomPath: string, workspace: string, driveWorkspaceId: string, uploadId: string, passphrase?: string | undefined | null): string

export declare function driveRenameJson(loomPath: string, workspace: string, driveWorkspaceId: string, folderId: string, nodeId: string, newName: string, expectedRoot: string, passphrase?: string | undefined | null): string

export declare function driveMoveJson(loomPath: string, workspace: string, driveWorkspaceId: string, sourceFolderId: string, targetFolderId: string, nodeId: string, expectedRoot: string, passphrase?: string | undefined | null): string

export declare function driveDeleteJson(loomPath: string, workspace: string, driveWorkspaceId: string, folderId: string, nodeId: string, expectedRoot: string, passphrase?: string | undefined | null): string

export declare function driveResolveConflictJson(loomPath: string, workspace: string, driveWorkspaceId: string, conflictId: string, resolution: string, passphrase?: string | undefined | null): string

export declare function driveGrantShareJson(loomPath: string, workspace: string, driveWorkspaceId: string, grantId: string, targetKind: string, targetId: string, principal: string, role: string, grantedAtMs: bigint, expiresAtMs?: bigint | null, passphrase?: string | undefined | null): string

export declare function driveRevokeShareJson(loomPath: string, workspace: string, driveWorkspaceId: string, grantId: string, passphrase?: string | undefined | null): string

export declare function driveApplyShareExpiryJson(loomPath: string, workspace: string, driveWorkspaceId: string, nowMs: bigint, passphrase?: string | undefined | null): string

export declare function drivePinRetentionJson(loomPath: string, workspace: string, driveWorkspaceId: string, pinId: string, kind: string, root: string, targetEntityId: string | undefined | null, addedAtMs: bigint, expiresAtMs?: bigint | null, passphrase?: string | undefined | null): string

export declare function driveUnpinRetentionJson(loomPath: string, workspace: string, driveWorkspaceId: string, pinId: string, passphrase?: string | undefined | null): string

export declare function driveApplyRetentionJson(loomPath: string, workspace: string, driveWorkspaceId: string, nowMs: bigint, passphrase?: string | undefined | null): string

export declare function ticketsProjectCreateJson(loomPath: string, workspace: string, ticketWorkspaceId: string, projectId: string, keyPrefix: string, name: string, expectedRoot?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function ticketsProjectRekeyJson(loomPath: string, workspace: string, ticketWorkspaceId: string, projectId: string, keyPrefix: string, expectedRoot?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function ticketsProjectSettingsGetJson(loomPath: string, workspace: string, ticketWorkspaceId: string, projectId: string, passphrase?: string | undefined | null): string

export declare function ticketsProjectSettingsSetJson(loomPath: string, workspace: string, ticketWorkspaceId: string, projectId: string, defaultProjection: string | undefined | null, enableProjectionsJson: string, disableProjectionsJson: string, actorEnforcement: string | undefined | null, projectOwnerPrincipal: string | undefined | null, clearProjectOwnerPrincipal: boolean, acceptanceAuthoritiesJson?: string | undefined | null, expectedRoot?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function ticketsFieldsJson(loomPath: string, workspace: string, ticketWorkspaceId: string, projectId?: string | undefined | null, projection?: string | undefined | null, operation?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function ticketsFieldPutJson(loomPath: string, workspace: string, ticketWorkspaceId: string, projectId: string, fieldId: string, key: string, name: string, description: string | undefined | null, fieldType: string, optionSet: string | undefined | null, maxLength: number | undefined | null, required: boolean, searchable: boolean, orderable: boolean, cardinality: string, applicableTypeIdsJson: string, expectedRoot?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function ticketsFieldRetireJson(loomPath: string, workspace: string, ticketWorkspaceId: string, projectId: string, fieldId: string, expectedRoot?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function ticketsCreateJson(loomPath: string, workspace: string, ticketWorkspaceId: string, projectId: string, ticketType: string, externalSource: string | undefined | null, externalId: string | undefined | null, fieldsJson: string, policyLabelsJson: string, expectedRoot?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function ticketsUpdateJson(loomPath: string, workspace: string, ticketWorkspaceId: string, ticketId: string, setFieldsJson: string | undefined | null, deleteFieldsJson: string, action?: string | undefined | null, targetStatus?: string | undefined | null, observedSourceStatus?: string | undefined | null, observedWorkflowVersion?: string | undefined | null, assignee?: string | undefined | null, commentId?: string | undefined | null, commentType?: string | undefined | null, commentBody?: string | undefined | null, expectedRoot?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function ticketsDeleteJson(loomPath: string, workspace: string, ticketWorkspaceId: string, ticketId: string, expectedRoot?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function ticketsRelationSetJson(loomPath: string, workspace: string, ticketWorkspaceId: string, ticketId: string, relationId: string | undefined | null, kind: string, targetId: string, expectedRoot?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function ticketsRelationRemoveJson(loomPath: string, workspace: string, ticketWorkspaceId: string, ticketId: string, relationId: string, expectedRoot?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function ticketsRelationListJson(loomPath: string, workspace: string, ticketWorkspaceId: string, ticketId: string, passphrase?: string | undefined | null): string

export declare function ticketsGetJson(loomPath: string, workspace: string, ticketWorkspaceId: string, ticketId: string, projection?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function ticketsListJson(loomPath: string, workspace: string, ticketWorkspaceId: string, projection?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function ticketsHistoryJson(loomPath: string, workspace: string, ticketWorkspaceId: string, ticketId?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function chatCreateChannelJson(loomPath: string, workspace: string, chatWorkspaceId: string, channelId: string, channelHandle: string, name: string, passphrase?: string | undefined | null): string

export declare function chatRenameChannelJson(loomPath: string, workspace: string, chatWorkspaceId: string, selector: string, channelHandle: string, passphrase?: string | undefined | null): string

export declare function chatListChannelsJson(loomPath: string, workspace: string, chatWorkspaceId: string, passphrase?: string | undefined | null): string

export declare function chatPostMessageJson(loomPath: string, workspace: string, chatWorkspaceId: string, channelId: string, messageId: string, threadId: string | undefined | null, bodyText: string, passphrase?: string | undefined | null): string

export declare function chatEditMessageJson(loomPath: string, workspace: string, chatWorkspaceId: string, channelId: string, messageId: string, bodyText: string, passphrase?: string | undefined | null): string

export declare function chatRedactMessageJson(loomPath: string, workspace: string, chatWorkspaceId: string, channelId: string, messageId: string, reasonText?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function chatCreateThreadJson(loomPath: string, workspace: string, chatWorkspaceId: string, channelId: string, threadId: string, parentMessageId: string, passphrase?: string | undefined | null): string

export declare function chatCreateTaskJson(loomPath: string, workspace: string, chatWorkspaceId: string, channelId: string, taskId: string, messageId: string | undefined | null, title: string, passphrase?: string | undefined | null): string

export declare function chatClaimTaskJson(loomPath: string, workspace: string, chatWorkspaceId: string, channelId: string, taskId: string, claimId: string, leaseToken?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function chatCompleteTaskJson(loomPath: string, workspace: string, chatWorkspaceId: string, channelId: string, taskId: string, claimId: string, resultMessageId?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function chatInvokeAgentJson(loomPath: string, workspace: string, chatWorkspaceId: string, channelId: string, invocationId: string, agentPrincipal: string, sourceMessageIdsJson: string, promptText: string, passphrase?: string | undefined | null): string

export declare function chatAgentReplyJson(loomPath: string, workspace: string, chatWorkspaceId: string, channelId: string, invocationId: string, messageId: string, passphrase?: string | undefined | null): string

export declare function chatRequestHandoffJson(loomPath: string, workspace: string, chatWorkspaceId: string, channelId: string, handoffId: string, fromAgentPrincipal: string, toPrincipal?: string | undefined | null, reasonText?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function chatAddReactionJson(loomPath: string, workspace: string, chatWorkspaceId: string, channelId: string, messageId: string, kind: string, passphrase?: string | undefined | null): string

export declare function chatRemoveReactionJson(loomPath: string, workspace: string, chatWorkspaceId: string, channelId: string, messageId: string, kind: string, passphrase?: string | undefined | null): string

export declare function chatEmojiListJson(loomPath: string, workspace: string, chatWorkspaceId: string, passphrase?: string | undefined | null): string

export declare function chatEmojiRegisterJson(loomPath: string, workspace: string, chatWorkspaceId: string, kind: string, passphrase?: string | undefined | null): string

export declare function chatEmojiUnregisterJson(loomPath: string, workspace: string, chatWorkspaceId: string, kind: string, passphrase?: string | undefined | null): string

export declare function chatMessagesJson(loomPath: string, workspace: string, chatWorkspaceId: string, channelId: string, passphrase?: string | undefined | null): string

export declare function chatCursorJson(loomPath: string, workspace: string, chatWorkspaceId: string, channelId: string, passphrase?: string | undefined | null): string

export declare function chatUpdateCursorJson(loomPath: string, workspace: string, chatWorkspaceId: string, channelId: string, nextSequence: bigint, passphrase?: string | undefined | null): string

export declare function chatFetchEventsJson(loomPath: string, workspace: string, chatWorkspaceId: string, channelId: string, fromSequence: bigint, max: number, passphrase?: string | undefined | null): string

/**
 * Abandon the in-progress merge, restoring the pre-merge working tree. Throws `INVALID_ARGUMENT` if no
 * merge is in progress.
 */
export declare function mergeAbort(loomPath: string, facet: string, workspace: string, passphrase?: string | undefined | null): void

/**
 * The still-unresolved conflict paths of the in-progress merge, in path order; empty when no merge is
 * in progress.
 */
export declare function mergeConflicts(loomPath: string, facet: string, workspace: string, passphrase?: string | undefined | null): Array<string>

/**
 * Finish the in-progress merge: record the two-parent merge commit and return its content address.
 * Throws `CONFLICT` if conflicts remain.
 */
export declare function mergeContinue(loomPath: string, facet: string, workspace: string, author: string, passphrase?: string | undefined | null): string

/**
 * Whether workspace `workspace` (selected with `facet`) has a conflicted merge awaiting `mergeContinue`
 * or `mergeAbort`.
 */
export declare function mergeInProgress(loomPath: string, facet: string, workspace: string, passphrase?: string | undefined | null): boolean

/**
 * Settle one conflicted `path` of the in-progress merge. `resolution` is `"ours"`, `"theirs"`, or
 * `"working"` (accept the currently staged content).
 */
export declare function mergeResolve(loomPath: string, facet: string, workspace: string, path: string, resolution: string, passphrase?: string | undefined | null): void

export declare function metricsGetDescriptor(loomPath: string, workspace: string, name: string, passphrase?: string | undefined | null): Uint8Array | null

export declare function metricsPutDescriptor(loomPath: string, workspace: string, descriptor: Uint8Array, passphrase?: string | undefined | null): void

export declare function metricsPutObservation(loomPath: string, workspace: string, descriptorName: string, observation: Uint8Array, passphrase?: string | undefined | null): void

export declare function metricsQuery(loomPath: string, workspace: string, descriptorName: string, fromTimestampMs: bigint, toTimestampMs: bigint, maxSeries: number, maxGroups: number, maxSamples: number, maxOutputBytes: bigint, passphrase?: string | undefined | null): Uint8Array

export declare function protectedRefGetJson(loomPath: string, workspace: string, refName: string, passphrase?: string | undefined | null, authPrincipal?: string | undefined | null, authPassphrase?: string | undefined | null): string

export declare function protectedRefListJson(loomPath: string, workspace: string, passphrase?: string | undefined | null, authPrincipal?: string | undefined | null, authPassphrase?: string | undefined | null): string

export declare function protectedRefRemove(loomPath: string, workspace: string, refName: string, passphrase?: string | undefined | null, authPrincipal?: string | undefined | null, authPassphrase?: string | undefined | null): boolean

export declare function protectedRefSet(loomPath: string, workspace: string, refName: string, fastForwardOnly: boolean, signedCommitsRequired: boolean, signedRefAdvanceRequired: boolean, requiredReviewCount: number, retentionLock: boolean, governanceLock: boolean, passphrase?: string | undefined | null, authPrincipal?: string | undefined | null, authPassphrase?: string | undefined | null): void

/**
 * Append `entry` to `stream` in a workspace (by UUID or name, created with the `queue` facet if
 * absent); returns the assigned zero-based sequence.
 */
export declare function queueAppend(loomPath: string, workspace: string, stream: string, entry: Uint8Array, passphrase?: string | undefined | null): bigint

/** Advance the named consumer's next sequence for `stream` to `nextSeq`; rejects backward movement. */
export declare function queueConsumerAdvance(loomPath: string, workspace: string, stream: string, consumerId: string, nextSeq: bigint, passphrase?: string | undefined | null): void

/** The named consumer's next sequence for `stream`; `0` when none is stored. */
export declare function queueConsumerPosition(loomPath: string, workspace: string, stream: string, consumerId: string, passphrase?: string | undefined | null): bigint

/** Read up to `max` entries from the consumer's stored next sequence in `stream`; does not advance. */
export declare function queueConsumerRead(loomPath: string, workspace: string, stream: string, consumerId: string, max: number, passphrase?: string | undefined | null): Array<Uint8Array>

/** Set the named consumer's next sequence for `stream` to `nextSeq`, which may move backward. */
export declare function queueConsumerReset(loomPath: string, workspace: string, stream: string, consumerId: string, nextSeq: bigint, passphrase?: string | undefined | null): void

/** Fetch the entry at `seq` in `stream`, or `null` if out of range. */
export declare function queueGet(loomPath: string, workspace: string, stream: string, seq: bigint, passphrase?: string | undefined | null): Uint8Array | null

/** The number of entries in `stream`. */
export declare function queueLen(loomPath: string, workspace: string, stream: string, passphrase?: string | undefined | null): bigint

/** Read the half-open range `[lo, hi)` of `stream`, oldest first. */
export declare function queueRange(loomPath: string, workspace: string, stream: string, lo: bigint, hi: bigint, passphrase?: string | undefined | null): Array<Uint8Array>

/**
 * Read up to `len` bytes from byte `offset` of file `path` (bounded chunk read; reads past the end
 * clamp). A missing file is an error.
 */
export declare function readAt(loomPath: string, facet: string, workspace: string, path: string, offset: number, len: number, passphrase?: string | undefined | null): Uint8Array

/** Read file `path` from the workspace working tree. */
export declare function readFile(loomPath: string, facet: string, workspace: string, path: string, passphrase?: string | undefined | null): Uint8Array

/** Read the target of the symbolic link at `path` (errors if absent or not a symlink). */
export declare function readLink(loomPath: string, facet: string, workspace: string, path: string, passphrase?: string | undefined | null): string

/**
 * Rebase the current branch onto `onto` (HEAD|branch|digest), replaying first-parent commits linearly.
 * `dryRun` previews conflicts. Returns the outcome JSON.
 */
export declare function rebase(loomPath: string, facet: string, workspace: string, onto: string, dryRun: boolean, passphrase?: string | undefined | null): string

/** Remove file `path` from the workspace working tree. */
export declare function removeFile(loomPath: string, facet: string, workspace: string, path: string, passphrase?: string | undefined | null): void

/**
 * Restore one `path` in the working tree to the snapshot `rev` resolves to (HEAD|branch|digest);
 * absent in the snapshot removes it. Working tree only.
 */
export declare function restoreFile(loomPath: string, facet: string, workspace: string, rev: string, path: string, passphrase?: string | undefined | null): void

/**
 * Restore the subtree under `prefix` to the snapshot `rev` resolves to (a `""` prefix restores the
 * whole tree). Working tree only.
 */
export declare function restorePath(loomPath: string, facet: string, workspace: string, rev: string, prefix: string, passphrase?: string | undefined | null): void

/**
 * Render a canonical-CBOR result buffer to lossless bridge JSON, the React Native bridge projection.
 * This is not the normative wire form and not the general typed API: values a JS number cannot hold
 * exactly (64/128-bit ints, decimals, bytes, uuids, non-finite floats, points) cross as tagged
 * `$`-prefixed objects. Mirrors the C ABI `loom_result_to_bridge_json`.
 */
export declare function resultToBridgeJson(bytes: Uint8Array): string

/**
 * Render a canonical-CBOR result buffer (from `exec`/`query` or a direct reader) to debug JSON. This is
 * a debug/inspection view, not the typed API: faithful cells decode to type-tagged scalars such as
 * `{"Int":1}` and `{"Text":"hi"}`. Mirrors the C ABI `loom_result_to_json`.
 */
export declare function resultToJson(bytes: Uint8Array): string

/**
 * Revert `commits` (digest strings) on the current branch as new commits authored by `author`.
 * `dryRun` previews conflicts. Returns the outcome JSON.
 */
export declare function revert(loomPath: string, facet: string, workspace: string, commits: Array<string>, author: string, dryRun: boolean, passphrase?: string | undefined | null): string

/** The runtime provider/profile report as canonical CBOR. */
export declare function runtimeProfile(): Uint8Array

export declare function studioSurfaceCatalogJson(workspace: string, set?: string | undefined | null): string

/**
 * Create search collection `name` with the field `mapping` (CBOR `field -> [type_tag, stored, faceted]`,
 * type 0 text, 1 keyword) in workspace `workspace` (UUID or name, created with the `search` facet if
 * absent). `CONFLICT` if the collection already exists.
 */
export declare function searchCreate(loomPath: string, workspace: string, name: string, mapping: Uint8Array, passphrase?: string | undefined | null): void

/**
 * Remove `id` from collection `name`; returns whether it was present. `NOT_FOUND` if the collection
 * does not exist.
 */
export declare function searchDelete(loomPath: string, workspace: string, name: string, id: Uint8Array, passphrase?: string | undefined | null): boolean

/**
 * Fetch the document at `id` in collection `name` as a CBOR `field -> value` map, or `null` if absent.
 * `NOT_FOUND` if the collection does not exist.
 */
export declare function searchGet(loomPath: string, workspace: string, name: string, id: Uint8Array, passphrase?: string | undefined | null): Uint8Array | null

/**
 * Document ids in collection `name` as the Loom Canonical CBOR array of byte strings. When `hasPrefix`
 * is true only ids starting with `prefix` are returned; otherwise every id is returned. `NOT_FOUND` if
 * the collection does not exist.
 */
export declare function searchIds(loomPath: string, workspace: string, name: string, prefix: Uint8Array, hasPrefix: boolean, passphrase?: string | undefined | null): Uint8Array

/**
 * Insert or replace the document at `id` (opaque bytes) in collection `name`; `doc` is a CBOR
 * `field -> value` map (each value text or bytes). `NOT_FOUND` if the collection was never created.
 */
export declare function searchIndex(loomPath: string, workspace: string, name: string, id: Uint8Array, doc: Uint8Array, passphrase?: string | undefined | null): void

/**
 * Run the portable linear-scan query over collection `name`. `request` is the CBOR array
 * `[query, limit, offset]` (`query` a recursive node: `[0, field, text]` match, `[1, field, value]`
 * term, `[2, field, [terms], slop]` phrase, `[3, field, lower, upper, incl_lower, incl_upper]` range,
 * `[4, [must], [should], [must_not]]` bool). The response is the CBOR array
 * `[reduced, [[id, score_cell, highlights] ...], facets, aggregations]`. `NOT_FOUND` if the collection
 * does not exist; `NO_SUCH_FIELD` for an unmapped query field.
 */
export declare function searchQuery(loomPath: string, workspace: string, name: string, request: Uint8Array, passphrase?: string | undefined | null): Uint8Array

/**
 * Replace the field mapping of collection `name` (CBOR `field -> [type_tag, stored, faceted]`).
 * `NOT_FOUND` if the collection does not exist.
 */
export declare function searchRemap(loomPath: string, workspace: string, name: string, mapping: Uint8Array, passphrase?: string | undefined | null): void

/**
 * Blame the rows of `table` on `branch` for workspace `workspace` (selected with `facet`): each current
 * row plus the commit that last set it, as canonical-CBOR
 * (`{ "rows": [ { "commit", "values" } ] }`). Mirrors the C ABI `loom_sql_blame`.
 */
export declare function sqlBlame(loomPath: string, workspace: string, branch: string, table: string, passphrase?: string | undefined | null): Uint8Array

/**
 * Row-level diff of `table` between commits `fromCommit` and `toCommit` (content addresses), as
 * canonical-CBOR (`{ "diffs": [...] }`). `workspace` is validated to exist under the sql facet.
 * Mirrors the C ABI `loom_sql_diff`.
 */
export declare function sqlDiff(loomPath: string, workspace: string, table: string, fromCommit: string, toCommit: string, passphrase?: string | undefined | null): Uint8Array

/**
 * Scan secondary index `index` on `table` for the lookup `prefix` (a canonical-CBOR cell array, the
 * same codec as a result row; an empty prefix is the canonical CBOR of an empty array), returning the
 * matching rows as canonical-CBOR (`{ "columns", "rows" }`). Mirrors the C ABI `loom_sql_index_scan`.
 */
export declare function sqlIndexScan(loomPath: string, workspace: string, table: string, index: string, prefix: Uint8Array, passphrase?: string | undefined | null): Uint8Array

/** Scan secondary index `index` on `table` from historical commit `commit`. */
export declare function sqlIndexScanAt(loomPath: string, workspace: string, table: string, index: string, prefix: Uint8Array, commit: string, passphrase?: string | undefined | null): Uint8Array

/**
 * Read the staged `table` of workspace `workspace` (selected with `facet`) as canonical-CBOR
 * (`{ "columns", "rows" }`). `table` is the staged table path, e.g.
 * `.loom/facets/sql/<db>/tables/<name>`. Mirrors the C ABI `loom_sql_read_table`.
 */
export declare function sqlReadTable(loomPath: string, workspace: string, table: string, passphrase?: string | undefined | null): Uint8Array

/** Read `table` from historical commit `commit`, leaving the current working tree unchanged. */
export declare function sqlReadTableAt(loomPath: string, workspace: string, table: string, commit: string, passphrase?: string | undefined | null): Uint8Array

/** Schema-aware table diff between commits. Existing `sqlDiff` remains row-only. */
export declare function sqlTableDiff(loomPath: string, workspace: string, table: string, fromCommit: string, toCommit: string, passphrase?: string | undefined | null): Uint8Array

/**
 * Squash the commits after `onto` up to the tip into one commit (`author`/`message`); returns the new
 * commit digest. `onto` must be an ancestor of the tip and not the tip itself.
 */
export declare function squash(loomPath: string, facet: string, workspace: string, onto: string, author: string, message: string, passphrase?: string | undefined | null): string

/** Stage `paths` into the workspace's shared index (one stage across all facets). */
export declare function stage(loomPath: string, facet: string, workspace: string, paths: Array<string>, passphrase?: string | undefined | null): void

/** Stage the entire working tree (every change across every facet) into the shared index. */
export declare function stageAll(loomPath: string, facet: string, workspace: string, passphrase?: string | undefined | null): void

/** The workspace status as a JSON string (`{ staged, unstaged, untracked, conflicts }`). */
export declare function statusJson(loomPath: string, facet: string, workspace: string, passphrase?: string | undefined | null): string

/**
 * Create a symbolic link at `linkPath` whose target is `target` (opaque; may be dangling). The parent
 * must exist; `linkPath` must be free.
 */
export declare function symlink(loomPath: string, facet: string, workspace: string, target: string, linkPath: string, passphrase?: string | undefined | null): void

/**
 * Create tag `name` at the commit `rev` resolves to (`HEAD`, a branch name, or a digest). A non-empty
 * `message` makes an annotated tag (with `tagger`); empty makes a lightweight tag. Returns the ref
 * target digest (the commit, or the tag object).
 */
export declare function tagCreate(loomPath: string, facet: string, workspace: string, name: string, rev: string, tagger?: string | undefined | null, message?: string | undefined | null, passphrase?: string | undefined | null): string

/** Delete tag `name` (errors if absent). */
export declare function tagDelete(loomPath: string, facet: string, workspace: string, name: string, passphrase?: string | undefined | null): void

/** All tag names in the workspace, sorted. */
export declare function tagList(loomPath: string, facet: string, workspace: string, passphrase?: string | undefined | null): Array<string>

/** Rename tag `oldName` to `newName`, preserving its target. */
export declare function tagRename(loomPath: string, facet: string, workspace: string, oldName: string, newName: string, passphrase?: string | undefined | null): void

/** The raw ref target digest of tag `name` (commit for lightweight, tag object for annotated), or null. */
export declare function tagTarget(loomPath: string, facet: string, workspace: string, name: string, passphrase?: string | undefined | null): string | null

export declare function tracesGetSpan(loomPath: string, workspace: string, traceId: string, spanId: string, passphrase?: string | undefined | null): Uint8Array | null

export declare function tracesPutSpan(loomPath: string, workspace: string, span: Uint8Array, passphrase?: string | undefined | null): void

export declare function tracesQuery(loomPath: string, workspace: string, fromStartTimeNs: bigint, toStartTimeNs: bigint, maxSpans: number, maxOutputBytes: bigint, passphrase?: string | undefined | null): Uint8Array

export declare function tracesTraceSpans(loomPath: string, workspace: string, traceId: string, maxSpans: number, maxOutputBytes: bigint, passphrase?: string | undefined | null): Uint8Array

/** Resize file `path` to `size`, zero-extending or dropping bytes; a missing file is created zero-filled. */
export declare function truncateFile(loomPath: string, facet: string, workspace: string, path: string, size: number, passphrase?: string | undefined | null): void

/** The point at timestamp `ts` in series `collection`, or `null` if absent. */
export declare function tsGet(loomPath: string, workspace: string, collection: string, ts: number, passphrase?: string | undefined | null): Uint8Array | null

/**
 * The most recent point of series `collection` as a one-point Loom Canonical CBOR array, or `null` if the
 * series is absent or empty.
 */
export declare function tsLatest(loomPath: string, workspace: string, collection: string, passphrase?: string | undefined | null): Uint8Array | null

/**
 * Put `value` at timestamp `ts` in series `collection` of `workspace` (created with the `time-series` facet if
 * absent); a repeated timestamp replaces the point.
 */
export declare function tsPut(loomPath: string, workspace: string, collection: string, ts: number, value: Uint8Array, passphrase?: string | undefined | null): void

/**
 * The points of series `collection` with `from <= ts < to` (half-open, time order) as the Loom Canonical CBOR
 * array of `[ts, value]` pairs.
 */
export declare function tsRange(loomPath: string, workspace: string, collection: string, from: number, to: number, passphrase?: string | undefined | null): Uint8Array

/** Unstage `paths`, reverting each index entry to its HEAD state. */
export declare function unstage(loomPath: string, facet: string, workspace: string, paths: Array<string>, passphrase?: string | undefined | null): void

/**
 * Workspace/entry-level blame for `branch` in workspace `workspace`: each current path plus the
 * commit that last set it, as canonical-CBOR
 * (`{ "kind": "PathBlame", "paths": [ { "path", "commit" } ] }`). Mirrors the C ABI `loom_vcs_blame`.
 */
export declare function vcsBlame(loomPath: string, workspace: string, branch: string, passphrase?: string | undefined | null): Uint8Array

/**
 * Cross-facet structural diff between two commits as the raw `LMDIFF` canonical-CBOR envelope.
 * Mirrors the C ABI `loom_vcs_diff`.
 */
export declare function vcsDiff(loomPath: string, workspace: string, fromCommit: string, toCommit: string, passphrase?: string | undefined | null): Uint8Array

/**
 * Create vector set `name` of width `dim` and `metric` (1 cosine, 2 L2, 3 dot) in workspace `workspace`
 * (UUID or name, created with the `vector` facet if absent). `CONFLICT` if the set already exists.
 */
export declare function vectorCreate(loomPath: string, workspace: string, name: string, dim: bigint, metric: number, passphrase?: string | undefined | null): void

/** Declare and build a metadata equality index for `key`; returns whether a new index was declared. */
export declare function vectorCreateMetadataIndex(loomPath: string, workspace: string, name: string, key: string, passphrase?: string | undefined | null): boolean

/** Remove `id` from set `name`; returns whether it was present. `NOT_FOUND` if the set does not exist. */
export declare function vectorDelete(loomPath: string, workspace: string, name: string, id: string, passphrase?: string | undefined | null): boolean

/** Drop a metadata equality index for `key`; returns whether an index was present. */
export declare function vectorDropMetadataIndex(loomPath: string, workspace: string, name: string, key: string, passphrase?: string | undefined | null): boolean

/** Fetch the set embedding model profile as CBOR `[1, model_id, dimension, weights_digest]`, or `null`. */
export declare function vectorEmbeddingModel(loomPath: string, workspace: string, name: string, passphrase?: string | undefined | null): Uint8Array | null

/**
 * Fetch the vector + metadata at `id` in set `name` as the Loom Canonical CBOR array `[vector_bytes,
 * metadata]` (`vector_bytes` little-endian `f32`; `metadata` a `text -> cell` map), or `null` if absent.
 * `NOT_FOUND` if the set does not exist.
 */
export declare function vectorGet(loomPath: string, workspace: string, name: string, id: string, passphrase?: string | undefined | null): Uint8Array | null

/**
 * Vector ids in set `name`, sorted ascending, as the Loom Canonical CBOR array of text. When
 * `prefix` is present, only ids starting with that string prefix are returned. `NOT_FOUND` if the set
 * does not exist.
 */
export declare function vectorIds(loomPath: string, workspace: string, name: string, prefix?: string | undefined | null, passphrase?: string | undefined | null): Uint8Array

/**
 * Metadata equality index keys declared for set `name`, sorted ascending, as the Loom Canonical CBOR
 * array of text. `NOT_FOUND` if the set does not exist.
 */
export declare function vectorMetadataIndexKeys(loomPath: string, workspace: string, name: string, passphrase?: string | undefined | null): Uint8Array

/**
 * Exact top-`k` nearest neighbours of `query` (bytes of little-endian `f32`) in set `name` among
 * vectors passing `filter`, as the Loom Canonical CBOR array of `[id, score_cell]`, highest score first.
 * The filter is a recursive CBOR array: `[0]` all, `[1, key, value_cell]` equality, `[2, a, b]` AND; an
 * empty buffer is all. `NOT_FOUND` if the set does not exist; `DIMENSION_MISMATCH` on a wrong-width query.
 */
export declare function vectorSearch(loomPath: string, workspace: string, name: string, query: Uint8Array, k: bigint, filter: Uint8Array, passphrase?: string | undefined | null): Uint8Array

/**
 * Top-`k` nearest neighbours with an explicit accelerator policy over the built-in PQ accelerator.
 * `policy` is 0 for exact and 1 for approximate-above-threshold. Results have the same CBOR shape
 * as `vectorSearch`.
 */
export declare function vectorSearchPolicy(loomPath: string, workspace: string, name: string, query: Uint8Array, k: bigint, filter: Uint8Array, policy: number, threshold: bigint, ef: bigint, pqM: bigint, pqK: bigint, pqIters: bigint, passphrase?: string | undefined | null): Uint8Array

/** Fetch UTF-8 source text for vector `id`, or `null` if no source text is stored. */
export declare function vectorSourceText(loomPath: string, workspace: string, name: string, id: string, passphrase?: string | undefined | null): Uint8Array | null

/**
 * Insert or replace the vector at `id` in set `name`: `vector` is bytes of little-endian `f32` (4 per
 * component); `metadata` is a CBOR `text -> cell` map (or empty). `NOT_FOUND` if the set was never
 * created; `DIMENSION_MISMATCH` on a wrong width.
 */
export declare function vectorUpsert(loomPath: string, workspace: string, name: string, id: string, vector: Uint8Array, metadata: Uint8Array, passphrase?: string | undefined | null): void

/**
 * Insert or replace a vector with UTF-8 source text and optional embedding model profile. The profile
 * crosses as `[1, model_id, dimension, weights_digest]`.
 */
export declare function vectorUpsertSource(loomPath: string, workspace: string, name: string, id: string, vector: Uint8Array, metadata: Uint8Array, sourceText: Uint8Array, modelId?: string | undefined | null, weightsDigest?: string | undefined | null, passphrase?: string | undefined | null): void

/** The library version. */
export declare function version(): string

/** Poll an opaque watch cursor and return a canonical-CBOR `loom.watch.batch.v1` batch. */
export declare function watchPoll(loomPath: string, cursor: string, max: number, passphrase?: string | undefined | null): Uint8Array

/** Subscribe to workspace history changes and return an opaque watch cursor string. */
export declare function watchSubscribe(loomPath: string, workspace: string, branch: string, facet?: string | undefined | null, pathPrefix?: string | undefined | null, changeKinds?: Array<string> | undefined | null, fromCommit?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function workspaceCreate(loomPath: string, name?: string | undefined | null, facet?: string | undefined | null, passphrase?: string | undefined | null): string

export declare function workspaceDelete(loomPath: string, workspace: string, passphrase?: string | undefined | null): void

export declare function workspaceListJson(loomPath: string, passphrase?: string | undefined | null): string

export declare function workspaceRename(loomPath: string, workspace: string, newName: string, passphrase?: string | undefined | null): void

/** Write `content` at byte `offset` of file `path`, creating it if absent and zero-filling any gap. */
export declare function writeAt(loomPath: string, facet: string, workspace: string, path: string, offset: number, content: Uint8Array, passphrase?: string | undefined | null): void

/**
 * Create-or-replace file `path` in the workspace working tree with `content` and `mode` (default
 * `0o100644`). The parent directory must exist.
 */
export declare function writeFile(loomPath: string, facet: string, workspace: string, path: string, content: Uint8Array, mode?: number | undefined | null, passphrase?: string | undefined | null): void
