//! Emit the Loom Remote Protocol artifacts from `idl/loom.idl`.
//!
//! The IDL is the single source of truth. This tool parses every `interface` block and
//! its methods and writes the committed files: the method registry and the `LoomApi` trait families in
//! `loom-remote-protocol`, and the `RemoteLoomClient` stubs in `loom-remote-client`. Output is formatted
//! through `rustfmt`, so
//! `cargo fmt --check` is a no-op on the generated files and `--check` here detects any drift from the
//! IDL. Regenerate with `cargo run -p uldren-loom-remote-codegen`.
//!
//! Licensed under BUSL-1.1.

use std::io::Write;
use std::path::PathBuf;
use std::process::{Command, ExitCode, Stdio};

struct Method {
    interface: String,
    name: String,
    ret: String,
    args: Vec<(String, String)>,
}

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
}

fn parse(idl: &str) -> Vec<Method> {
    let mut methods = Vec::new();
    let mut interface: Option<String> = None;
    let mut buffer = String::new();
    for raw in idl.lines() {
        let line = raw.trim();
        if let Some(rest) = line.strip_prefix("interface ") {
            interface = rest.split_whitespace().next().map(str::to_string);
            buffer.clear();
            continue;
        }
        let Some(current) = interface.as_deref() else {
            continue;
        };
        if line == "}" {
            interface = None;
            buffer.clear();
            continue;
        }
        if line.is_empty() || line.starts_with("//") {
            continue;
        }
        if !buffer.is_empty() {
            buffer.push(' ');
        }
        buffer.push_str(line);
        if buffer.trim_end().ends_with(");") {
            if let Some(method) = parse_signature(current, &buffer) {
                methods.push(method);
            }
            buffer.clear();
        }
    }
    methods
}

fn parse_signature(interface: &str, signature: &str) -> Option<Method> {
    let signature = signature.trim().trim_end_matches(';').trim();
    let open = signature.find('(')?;
    let close = signature.rfind(')')?;
    let head = signature[..open].trim();
    let params = &signature[open + 1..close];

    let mut head_tokens: Vec<&str> = head.split_whitespace().collect();
    let name = head_tokens.pop()?.to_string();
    let ret = head_tokens.join(" ");
    let ret = if ret.is_empty() {
        "void".to_string()
    } else {
        ret
    };

    let mut args = Vec::new();
    for param in params.split(',') {
        let param = param.trim();
        if param.is_empty() {
            continue;
        }
        let mut tokens: Vec<&str> = param.split_whitespace().collect();
        let arg_name = tokens.pop()?.to_string();
        let arg_type = tokens.join(" ");
        args.push((arg_type, arg_name));
    }

    Some(Method {
        interface: interface.to_string(),
        name,
        ret,
        args,
    })
}

// ---- registry emitter ---------------------------------------------------------------------------

fn render_registry(methods: &[Method]) -> String {
    let mut out = String::new();
    out.push_str("//! Generated by `uldren-loom-remote-codegen` from `idl/loom.idl`. Do not edit by hand.\n//!\n//! Regenerate with `cargo run -p uldren-loom-remote-codegen`.\n\n");
    out.push_str("/// One IDL method signature, generated from `idl/loom.idl`.\n");
    out.push_str("#[derive(Debug, Clone, Copy)]\n");
    out.push_str("pub struct MethodSig {\n");
    out.push_str("    /// The IDL interface name.\n    pub interface: &'static str,\n");
    out.push_str("    /// The IDL method name.\n    pub method: &'static str,\n");
    out.push_str("    /// The argument `(type, name)` pairs in declaration order.\n    pub args: &'static [(&'static str, &'static str)],\n");
    out.push_str("    /// The IDL return type.\n    pub ret: &'static str,\n");
    out.push_str("}\n\n");
    out.push_str("/// Every method declared in `idl/loom.idl`, in file order.\n");
    out.push_str("pub const METHODS: &[MethodSig] = &[\n");
    for method in methods {
        let args = method
            .args
            .iter()
            .map(|(ty, name)| format!("({ty:?}, {name:?})"))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "    MethodSig {{ interface: {:?}, method: {:?}, args: &[{}], ret: {:?} }},\n",
            method.interface, method.name, args, method.ret
        ));
    }
    out.push_str("];\n");
    out
}

// ---- trait API emitter --------------------------------------------------------------------------

/// Methods that never perform I/O (transport `Lo`): they are plain `fn`, not `async`.
fn is_sync(interface: &str, method: &str) -> bool {
    matches!(
        (interface, method),
        ("ResultViews", _)
            | ("Diagnostics", "result_to_json")
            | ("Diagnostics", "result_to_bridge_json")
            | ("Diagnostics", "last_error")
            | ("Store", "blob_digest")
            | ("Tasks", "iter_free")
            | ("Tasks", "task_free")
    )
}

/// The methods the parity matrix classifies `key` (specs/0067 §12): mutating operations that are not
/// naturally idempotent, so §6 requires an idempotency key. Generated clients auto-attach a key for these
/// so a transport retry cannot double-apply them; the lower-level `RemoteLoomClient::call` still accepts a
/// caller-supplied key for durable app-level retries. This list is kept identical to the `| key |` rows of
/// the §12 matrix; `sql_exec_async` is on `Tasks`, and `append` is distinct on Columnar/Ledger/Queue.
fn requires_idempotency_key(interface: &str, method: &str) -> bool {
    matches!(
        (interface, method),
        ("KeySource", "key_add_wrap_keyed")
            | ("KeySource", "key_add_wrap_with_kek")
            | ("KeySource", "key_remove_wrap")
            | ("Exec", "exec_cbor")
            | ("Identity", "identity_add_principal")
            | ("Identity", "identity_create_external_credential")
            | ("Identity", "identity_add_public_key")
            | ("Identity", "identity_create_app_credential")
            | ("VersionControl", "merge")
            | ("VersionControl", "merge_continue")
            | ("VersionControl", "merge_async")
            | ("VersionControl", "squash")
            | ("FileSystem", "append_file")
            | ("Columnar", "append")
            | ("Ledger", "append")
            | ("Queue", "append")
            | ("Lanes", "create")
            | ("Lanes", "update")
            | ("Lanes", "ticket_add")
            | ("Lanes", "ticket_remove")
            | ("Sql", "sql_exec")
            | ("Sql", "sql_batch_exec")
            | ("Sql", "sql_batch_commit")
            | ("Sql", "sql_batch_commit_vcs")
            | ("Tasks", "sql_exec_async")
            | ("Transfer", "transfer_import_open")
            | ("Transfer", "transfer_import_write")
            | ("Transfer", "transfer_import_finish")
            | ("StoreAdmin", "store_policy_set")
            | ("StoreAdmin", "store_rekey")
    )
}

/// Map an IDL type to the wire-level Rust type used by the generated trait surface. Named composite
/// types (structs and enums) cross as canonical CBOR `Vec<u8>`, matching the IDL's own use of `bytes`
/// for structured payloads.
fn map_type(ty: &str) -> String {
    let ty = ty.trim();
    if let Some(inner) = ty.strip_prefix("optional ") {
        return format!("Option<{}>", map_type(inner));
    }
    if let Some(inner) = ty.strip_suffix('?') {
        return format!("Option<{}>", map_type(inner));
    }
    if let Some(rest) = ty.strip_prefix("list<") {
        let inner = rest.strip_suffix('>').unwrap_or(rest);
        return format!("Vec<{}>", map_type(inner));
    }
    if let Some(rest) = ty.strip_prefix("stream<") {
        let inner = rest.strip_suffix('>').unwrap_or(rest);
        return format!("LoomStream<{}>", map_type(inner));
    }
    match ty {
        "void" => "()".to_string(),
        "bool" | "i32" | "i64" | "u32" | "u64" | "f64" => ty.to_string(),
        "string" => "String".to_string(),
        "bytes" => "Vec<u8>".to_string(),
        "Uuid" => "Uuid".to_string(),
        "Digest" => "Digest".to_string(),
        "LoomSession" | "SqlSession" | "SqlBatch" | "RowIter" | "Task" | "ResultView" => {
            ty.to_string()
        }
        _ => "Vec<u8>".to_string(),
    }
}

const RUST_KEYWORDS: &[&str] = &[
    "as", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern", "false", "fn",
    "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
    "return", "self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use",
    "where", "while", "async", "await",
];

fn ident(name: &str) -> String {
    if RUST_KEYWORDS.contains(&name) {
        format!("r#{name}")
    } else {
        name.to_string()
    }
}

fn render_api(methods: &[Method]) -> String {
    let mut order: Vec<String> = Vec::new();
    for method in methods {
        if !order.contains(&method.interface) {
            order.push(method.interface.clone());
        }
    }

    let mut out = String::new();
    out.push_str("//! Generated by `uldren-loom-remote-codegen` from `idl/loom.idl`. Do not edit by hand.\n//!\n//! The `LoomApi` trait families: one trait per IDL interface plus the `LoomClient`\n//! supertrait. Methods that can perform a remote round trip return `impl Future + Send`; local-only\n//! methods (transport `Lo`) are plain `fn`. Regenerate with\n//! `cargo run -p uldren-loom-remote-codegen`.\n\n");
    out.push_str("// Generated bindings mirror the fixed IDL argument lists verbatim, so wide method\n// signatures are intentional.\n#![allow(clippy::too_many_arguments)]\n\n");
    out.push_str("use crate::api_types::{Digest, LoomSession, LoomStream, ResultView, RowIter, SqlBatch, SqlSession, Task, Uuid};\n");
    out.push_str("use loom_types::LoomError;\n\n");

    for interface in &order {
        out.push_str(&format!(
            "/// Generated trait for the IDL `{interface}` interface.\n"
        ));
        out.push_str(&format!("pub trait {interface} {{\n"));
        for method in methods.iter().filter(|m| &m.interface == interface) {
            let mut params = String::from("&self");
            for (ty, name) in &method.args {
                if name == "loom_path" {
                    continue;
                }
                params.push_str(&format!(", {}: {}", ident(name), map_type(ty)));
            }
            let ret = map_type(&method.ret);
            if is_sync(interface, &method.name) {
                out.push_str(&format!(
                    "    /// Generated binding for `{}.{}`.\n    fn {}({}) -> Result<{}, LoomError>;\n",
                    interface,
                    method.name,
                    ident(&method.name),
                    params,
                    ret
                ));
            } else {
                out.push_str(&format!(
                    "    /// Generated binding for `{}.{}`.\n    fn {}({}) -> impl ::core::future::Future<Output = Result<{}, LoomError>> + Send;\n",
                    interface,
                    method.name,
                    ident(&method.name),
                    params,
                    ret
                ));
            }
        }
        out.push_str("}\n\n");
    }

    out.push_str(
        "/// The full client surface: every generated interface trait plus `Send + Sync`.\n",
    );
    out.push_str(&format!(
        "pub trait LoomClient: {} + Send + Sync {{}}\n",
        order.join(" + ")
    ));
    out
}

// ---- client stub emitter ------------------------------------------------------------------------

/// The inner type of an `optional X` / `X?`, if any.
fn strip_optional(ty: &str) -> Option<String> {
    let ty = ty.trim();
    if let Some(inner) = ty.strip_prefix("optional ") {
        return Some(inner.trim().to_string());
    }
    ty.strip_suffix('?').map(|inner| inner.trim().to_string())
}

/// The inner type of a `list<X>`, if any.
fn strip_list(ty: &str) -> Option<String> {
    let ty = ty.trim();
    ty.strip_prefix("list<")
        .and_then(|rest| rest.strip_suffix('>'))
        .map(|inner| inner.trim().to_string())
}

/// The inner type of a `stream<X>`, if any.
fn strip_stream(ty: &str) -> Option<String> {
    let ty = ty.trim();
    ty.strip_prefix("stream<")
        .and_then(|rest| rest.strip_suffix('>'))
        .map(|inner| inner.trim().to_string())
}

/// A Rust expression encoding `expr` (of the mapped type for IDL `ty`) into a `loom_codec::Value`.
fn encode_expr(ty: &str, expr: &str) -> String {
    if let Some(inner) = strip_optional(ty) {
        return format!(
            "match {expr} {{ Some(inner) => {{ {} }}, None => ::loom_codec::Value::Null }}",
            encode_expr(&inner, "inner")
        );
    }
    if let Some(inner) = strip_list(ty) {
        return format!(
            "::loom_codec::Value::Array({expr}.into_iter().map(|item| {{ {} }}).collect())",
            encode_expr(&inner, "item")
        );
    }
    // `bytes` and every named composite record cross as a canonical CBOR byte string.
    if map_type(ty) == "Vec<u8>" {
        return format!("::loom_codec::Value::Bytes({expr})");
    }
    // Scalars, `String`, `Uuid`, `Digest`, and handle newtypes all have a `ToValue` impl.
    format!("::loom_remote_protocol::codec::ToValue::to_value(&{expr})")
}

/// A Rust expression decoding `expr` (a `loom_codec::Value`) into `Result<mapped, LoomError>`.
fn decode_expr(ty: &str, expr: &str) -> String {
    if let Some(inner) = strip_optional(ty) {
        return format!(
            "match {expr} {{ ::loom_codec::Value::Null => Ok(None), other => Ok(Some({}?)) }}",
            decode_expr(&inner, "other")
        );
    }
    if let Some(inner) = strip_list(ty) {
        return format!(
            "match {expr} {{ ::loom_codec::Value::Array(items) => items.into_iter().map(|item| {{ {} }}).collect::<::core::result::Result<Vec<_>, _>>(), _ => Err(crate::wire::shape(\"list\")) }}",
            decode_expr(&inner, "item")
        );
    }
    let mapped = map_type(ty);
    if mapped == "()" {
        return format!("{{ let _ = {expr}; Ok(()) }}");
    }
    if mapped == "Vec<u8>" {
        return format!(
            "match {expr} {{ ::loom_codec::Value::Bytes(bytes) => Ok(bytes), _ => Err(crate::wire::shape(\"bytes\")) }}"
        );
    }
    format!("crate::wire::from_wire::<{mapped}>(&{expr})")
}

fn render_client(methods: &[Method]) -> String {
    let mut order: Vec<String> = Vec::new();
    for method in methods {
        if !order.contains(&method.interface) {
            order.push(method.interface.clone());
        }
    }

    let mut out = String::new();
    out.push_str("//! Generated by `uldren-loom-remote-codegen` from `idl/loom.idl`. Do not edit by hand.\n//!\n//! The `RemoteLoomClient` implementations of the generated `LoomApi` traits.\n//! Every round-trip method forwards to `RemoteLoomClient::call` (unary) or `open_stream` (streams),\n//! encoding its arguments and decoding the reply through the shared codec; every local (`Lo`) method\n//! defers to the hand-written `lo_*` helpers in `local_ops.rs`. Regenerate with\n//! `cargo run -p uldren-loom-remote-codegen`.\n\n");
    // Generated argument lists mirror the IDL verbatim; the uniform `list<bytes>` encode closure is
    // mechanically emitted rather than hand-simplified.
    out.push_str("#![allow(clippy::too_many_arguments, clippy::redundant_closure)]\n\n");
    out.push_str("use crate::client::{CallOptions, RemoteLoomClient};\n");
    out.push_str("use crate::transport::Transport;\n");
    out.push_str("use loom_remote_protocol::api_types::{Digest, LoomSession, LoomStream, ResultView, RowIter, SqlBatch, SqlSession, Task, Uuid};\n");
    out.push_str("use loom_remote_protocol::generated_api::*;\n");
    out.push_str("use loom_types::LoomError;\n\n");

    for interface in &order {
        out.push_str(&format!(
            "impl<T: Transport + Send + Sync> {interface} for RemoteLoomClient<T> {{\n"
        ));
        for method in methods.iter().filter(|m| &m.interface == interface) {
            let name = ident(&method.name);
            let mut params = String::from("&self");
            let mut arg_idents: Vec<String> = Vec::new();
            for (ty, arg) in &method.args {
                if arg == "loom_path" {
                    continue;
                }
                params.push_str(&format!(", {}: {}", ident(arg), map_type(ty)));
                arg_idents.push(ident(arg));
            }
            let ret = map_type(&method.ret);

            if is_sync(interface, &method.name) {
                // Local (`Lo`) method: defer to the hand-written helper.
                let call_args = arg_idents.join(", ");
                out.push_str(&format!(
                    "    fn {name}({params}) -> Result<{ret}, LoomError> {{\n        self.lo_{}({call_args})\n    }}\n",
                    method.name
                ));
                continue;
            }

            // Build the argument value list once, shared by unary and stream forms.
            let mut arg_values = String::new();
            for (ty, arg) in method.args.iter().filter(|(_, a)| a != "loom_path") {
                arg_values.push_str(&format!("            {},\n", encode_expr(ty, &ident(arg))));
            }

            out.push_str(&format!(
                "    fn {name}({params}) -> impl ::core::future::Future<Output = Result<{ret}, LoomError>> + Send {{\n"
            ));
            out.push_str(&format!(
                "        let args: Vec<::loom_codec::Value> = vec![\n{arg_values}        ];\n"
            ));
            if let Some(_inner) = strip_stream(&method.ret) {
                out.push_str(&format!(
                    "        async move {{\n            let stream = self.open_stream({:?}, {:?}, args).await?;\n            Ok(crate::wire::into_loom_stream(stream))\n        }}\n",
                    interface, method.name
                ));
            } else {
                let options_expr = if requires_idempotency_key(interface, &method.name) {
                    "&self.idempotency_options()"
                } else {
                    "&CallOptions::default()"
                };
                out.push_str(&format!(
                    "        async move {{\n            let value = self.call({:?}, {:?}, args, {}).await?;\n            {}\n        }}\n",
                    interface,
                    method.name,
                    options_expr,
                    decode_expr(&method.ret, "value")
                ));
            }
            out.push_str("    }\n");
        }
        out.push_str("}\n\n");
    }

    out.push_str("/// `RemoteLoomClient` is the full generated client surface.\n");
    out.push_str("impl<T: Transport + Send + Sync> LoomClient for RemoteLoomClient<T> {}\n");
    out
}

// ---- server dispatch emitter --------------------------------------------------------------------

/// A Rust expression decoding a `&loom_codec::Value` (`{expr}`) into `Result<mapped, LoomError>` for
/// server-side argument decode. This is the inverse of the client's `encode_expr`: same shapes, but
/// using the server-visible `loom_remote_protocol::codec` traits and `InvalidArgument` on a bad shape.
fn dispatch_decode(ty: &str, expr: &str) -> String {
    if let Some(inner) = strip_optional(ty) {
        return format!(
            "match {expr} {{ ::loom_codec::Value::Null => Ok(None), other => Ok(Some({}?)) }}",
            dispatch_decode(&inner, "other")
        );
    }
    if let Some(inner) = strip_list(ty) {
        return format!(
            "match {expr} {{ ::loom_codec::Value::Array(items) => items.iter().map(|item| {{ {} }}).collect::<::core::result::Result<Vec<_>, _>>(), _ => Err(shape(\"list\")) }}",
            dispatch_decode(&inner, "item")
        );
    }
    // `bytes` and every named composite record cross as a canonical CBOR byte string.
    if map_type(ty) == "Vec<u8>" {
        return format!(
            "match {expr} {{ ::loom_codec::Value::Bytes(bytes) => Ok(bytes.clone()), _ => Err(shape(\"bytes\")) }}"
        );
    }
    let mapped = map_type(ty);
    format!(
        "<{mapped} as ::loom_remote_protocol::codec::FromValue>::from_value({expr}).map_err(arg_err)"
    )
}

/// A Rust expression encoding an owned reply `expr` (of the mapped type for IDL `ty`) into a
/// `loom_codec::Value`. Reuses the client's `encode_expr`; `void` crosses as `Null`.
fn dispatch_encode_ret(ty: &str, expr: &str) -> String {
    if map_type(ty) == "()" {
        return format!("{{ let _ = {expr}; ::loom_codec::Value::Null }}");
    }
    encode_expr(ty, expr)
}

fn render_dispatch(methods: &[Method]) -> String {
    let mut out = String::new();
    out.push_str("//! Generated by `uldren-loom-remote-codegen` from `idl/loom.idl`. Do not edit by hand.\n//!\n//! The server dispatch that decodes a decoded request, calls the generated `LoomClient` service trait\n//! on `LocalLoomClient`, and encodes the reply with the same canonical codec rules as the generated\n//! `RemoteLoomClient`. Regenerate with `cargo run -p uldren-loom-remote-codegen`.\n\n");
    out.push_str("#![allow(clippy::too_many_arguments, clippy::redundant_closure, clippy::match_single_binding)]\n\n");
    out.push_str("use loom_client::LocalLoomClient;\n");
    out.push_str("use loom_remote_protocol::api_types::{Digest, LoomSession, LoomStream, ResultView, RowIter, SqlBatch, SqlSession, Task, Uuid};\n");
    out.push_str("use loom_remote_protocol::generated_api::*;\n");
    out.push_str("use loom_types::{Code, LoomError};\n\n");

    out.push_str("/// The outcome of a generated dispatch: a unary reply value or a buffered stream of item payloads.\n");
    out.push_str("pub enum Dispatched {\n    /// A unary reply value.\n    Unary(::loom_codec::Value),\n    /// A buffered stream of canonical-CBOR item payloads.\n    Stream(Vec<Vec<u8>>),\n}\n\n");

    out.push_str("fn shape(expected: &str) -> LoomError {\n    LoomError::new(Code::InvalidArgument, format!(\"unexpected argument shape (expected {expected})\"))\n}\n\n");
    out.push_str("fn arg_err(err: ::loom_remote_protocol::codec::ArgError) -> LoomError {\n    LoomError::new(Code::InvalidArgument, format!(\"argument decode failed: {err}\"))\n}\n\n");
    out.push_str("fn take(args: &[::loom_codec::Value], idx: usize) -> Result<&::loom_codec::Value, LoomError> {\n    args.get(idx).ok_or_else(|| LoomError::new(Code::InvalidArgument, \"missing request argument\"))\n}\n\n");
    out.push_str("/// Poll an immediately-ready `LocalLoomClient` future once and flatten the result. In-process\n/// futures never pend; a `Pending` is a bug, reported as `INTERNAL` rather than spun on.\nfn poll_ready<T>(fut: impl ::core::future::Future<Output = Result<T, LoomError>>) -> Result<T, LoomError> {\n    let mut fut = ::std::pin::pin!(fut);\n    match fut\n        .as_mut()\n        .poll(&mut ::core::task::Context::from_waker(::std::task::Waker::noop()))\n    {\n        ::core::task::Poll::Ready(output) => output,\n        ::core::task::Poll::Pending => Err(LoomError::new(\n            Code::Internal,\n            \"in-process future returned Pending\",\n        )),\n    }\n}\n\n");
    out.push_str("/// Drain a buffered `LoomStream` into its item payloads for the buffered stream response. In-process\n/// streams never pend; a `Pending` is a bug, reported as `INTERNAL`.\nfn drain_stream(mut stream: LoomStream<Vec<u8>>) -> Result<Vec<Vec<u8>>, LoomError> {\n    let mut cx = ::core::task::Context::from_waker(::std::task::Waker::noop());\n    let mut items = Vec::new();\n    loop {\n        match stream.as_mut().poll_next(&mut cx) {\n            ::core::task::Poll::Ready(Some(Ok(item))) => items.push(item),\n            ::core::task::Poll::Ready(Some(Err(err))) => return Err(err),\n            ::core::task::Poll::Ready(None) => return Ok(items),\n            ::core::task::Poll::Pending => {\n                return Err(LoomError::new(\n                    Code::Internal,\n                    \"in-process stream returned Pending\",\n                ));\n            }\n        }\n    }\n}\n\n");

    out.push_str("/// Decode one request onto the `LoomClient` trait implemented by `LocalLoomClient`. The wire `handle`\n/// (a `LoomSession`) is decoded-and-discarded: the runtime substitutes its resolved `engine` session.\npub fn dispatch(\n    client: &LocalLoomClient,\n    engine: &LoomSession,\n    interface: &str,\n    method: &str,\n    args: &[::loom_codec::Value],\n) -> Result<Dispatched, LoomError> {\n    match (interface, method) {\n");

    for method in methods {
        let iface = &method.interface;
        let mut bindings = String::new();
        let mut call_args: Vec<String> = Vec::new();
        let mut wire_idx = 0usize;
        for (ty, name) in &method.args {
            if name == "loom_path" {
                continue;
            }
            if name == "handle" && ty == "LoomSession" {
                call_args.push("engine.clone()".to_string());
                wire_idx += 1;
                continue;
            }
            let id = ident(name);
            let mapped = map_type(ty);
            bindings.push_str(&format!(
                "            let {id} = {{\n                let __v = take(args, {wire_idx})?;\n                let __decoded: ::core::result::Result<{mapped}, LoomError> = {{ {} }};\n                __decoded\n            }}?;\n",
                dispatch_decode(ty, "__v")
            ));
            call_args.push(id);
            wire_idx += 1;
        }
        let sep = if call_args.is_empty() { "" } else { ", " };
        let call = format!(
            "<LocalLoomClient as {iface}>::{}(client{sep}{})",
            ident(&method.name),
            call_args.join(", ")
        );
        out.push_str(&format!("        ({iface:?}, {:?}) => {{\n", method.name));
        out.push_str(&bindings);
        if strip_stream(&method.ret).is_some() {
            out.push_str(&format!("            let stream = poll_ready({call})?;\n"));
            out.push_str("            Ok(Dispatched::Stream(drain_stream(stream)?))\n");
        } else {
            let call_expr = if is_sync(iface, &method.name) {
                format!("{call}?")
            } else {
                format!("poll_ready({call})?")
            };
            if map_type(&method.ret) == "()" {
                // Void reply: run the call for its effect and encode `Null` without binding a unit value.
                out.push_str(&format!("            {call_expr};\n"));
                out.push_str("            Ok(Dispatched::Unary(::loom_codec::Value::Null))\n");
            } else {
                out.push_str(&format!("            let out = {call_expr};\n"));
                out.push_str(&format!(
                    "            Ok(Dispatched::Unary({}))\n",
                    dispatch_encode_ret(&method.ret, "out")
                ));
            }
        }
        out.push_str("        }\n");
    }

    out.push_str("        _ => Err(LoomError::new(Code::NotFound, format!(\"unknown method {interface}.{method}\"))),\n");
    out.push_str("    }\n}\n");
    out
}

fn rustfmt(source: &str) -> String {
    let mut child = match Command::new("rustfmt")
        .arg("--edition")
        .arg("2024")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
    {
        Ok(child) => child,
        Err(_) => return source.to_string(),
    };
    if let Some(mut stdin) = child.stdin.take()
        && stdin.write_all(source.as_bytes()).is_err()
    {
        return source.to_string();
    }
    match child.wait_with_output() {
        Ok(output) if output.status.success() => {
            String::from_utf8_lossy(&output.stdout).to_string()
        }
        _ => source.to_string(),
    }
}

struct Artifact {
    path: PathBuf,
    content: String,
}

fn main() -> ExitCode {
    let check = std::env::args().any(|a| a == "--check");
    let root = repo_root();
    let idl_path = root.join("idl").join("loom.idl");

    let idl = match std::fs::read_to_string(&idl_path) {
        Ok(text) => text,
        Err(err) => {
            eprintln!("cannot read {}: {err}", idl_path.display());
            return ExitCode::FAILURE;
        }
    };
    let methods = parse(&idl);

    let artifacts = [
        Artifact {
            path: root
                .join("crates")
                .join("loom-remote-protocol")
                .join("src")
                .join("generated.rs"),
            content: rustfmt(&render_registry(&methods)),
        },
        Artifact {
            path: root
                .join("crates")
                .join("loom-remote-protocol")
                .join("src")
                .join("generated_api.rs"),
            content: rustfmt(&render_api(&methods)),
        },
        Artifact {
            path: root
                .join("crates")
                .join("loom-remote-client")
                .join("src")
                .join("generated_client.rs"),
            content: rustfmt(&render_client(&methods)),
        },
        Artifact {
            path: root
                .join("crates")
                .join("loom-hosted-core")
                .join("src")
                .join("generated_dispatch.rs"),
            content: rustfmt(&render_dispatch(&methods)),
        },
    ];

    let mut stale = false;
    for artifact in &artifacts {
        if check {
            let current = std::fs::read_to_string(&artifact.path).unwrap_or_default();
            if current != artifact.content {
                eprintln!("stale: {}", artifact.path.display());
                stale = true;
            }
        } else if let Err(err) = std::fs::write(&artifact.path, &artifact.content) {
            eprintln!("cannot write {}: {err}", artifact.path.display());
            return ExitCode::FAILURE;
        } else {
            println!("wrote {}", artifact.path.display());
        }
    }

    if check && stale {
        eprintln!("run `cargo run -p uldren-loom-remote-codegen` to regenerate");
        return ExitCode::FAILURE;
    }
    if check {
        println!(
            "generated artifacts are up to date ({} methods)",
            methods.len()
        );
    }
    ExitCode::SUCCESS
}
